// Embeds every PTX kernel in ptx/ (generated by tools/gen_ptx.sh) into the binary, as a table the CUDA backend
// looks kernels up in by file name.
use std::{env, fs, path::Path};

fn main() {
    let root = env::var("CARGO_MANIFEST_DIR").unwrap();
    let dir = Path::new(&root).join("ptx");
    println!("cargo:rerun-if-changed={}", dir.display());
    let mut files: Vec<_> = fs::read_dir(&dir)
        .map(|entries| {
            entries
                .filter_map(|e| e.ok().map(|e| e.path()))
                .filter(|p| p.extension().is_some_and(|x| x == "ptx"))
                .collect()
        })
        .unwrap_or_default();
    files.sort();
    let mut table = String::from("pub static PTX: &[(&str, &str)] = &[\n");
    for path in files {
        println!("cargo:rerun-if-changed={}", path.display());
        let name = path.file_name().unwrap().to_string_lossy();
        table.push_str(&format!(
            "    ({name:?}, include_str!({:?})),\n",
            path.display().to_string()
        ));
    }
    table.push_str("];\n");
    fs::write(
        Path::new(&env::var("OUT_DIR").unwrap()).join("ptx_table.rs"),
        table,
    )
    .unwrap();
}
