// GENERATED by tools/gen_wgsl.mjs from the OpenDLSS-NR browser-webgpu port: FP8 GEMM gemm_dual_batched.wgsl. Do not edit.

enable f16;
fn nr_round_half(value: f32) -> f32 {
  let bits = bitcast<u32>(value);
  let sign = bits & 0x80000000u;
  let magnitude = bits & 0x7fffffffu;
  if (magnitude >= 0x7f800000u) { return value; }
  if (magnitude >= 0x477ff000u) { return bitcast<f32>(sign | 0x7f800000u); }
  if (magnitude >= 0x38800000u) {
    return bitcast<f32>(sign | ((magnitude + 0xfffu + ((magnitude >> 13u) & 1u)) & 0xffffe000u));
  }
  let exponent = magnitude >> 23u;
  if (exponent < 102u) { return bitcast<f32>(sign); }
  let mantissa = (magnitude & 0x7fffffu) | 0x800000u;
  let shift = 126u - exponent;
  var units = mantissa >> shift;
  let remainder = mantissa & ((1u << shift) - 1u);
  let halfway = 1u << (shift - 1u);
  if (remainder > halfway || (remainder == halfway && (units & 1u) != 0u)) { units += 1u; }
  return bitcast<f32>(sign | bitcast<u32>(f32(units) * 5.9604644775390625e-8));
}
fn nr_round_half4(value: vec4<f32>) -> vec4<f32> {
  // The normal half range, [2^-14, 65520), is nearly every value: there it is one vectorized mantissa
  // rounding. Anything else takes the scalar path above.
  let bits = bitcast<vec4<u32>>(value);
  let magnitude = bits & vec4<u32>(0x7fffffffu);
  if (any(magnitude < vec4<u32>(0x38800000u)) || any(magnitude >= vec4<u32>(0x477ff000u))) {
    return vec4<f32>(nr_round_half(value.x), nr_round_half(value.y), nr_round_half(value.z), nr_round_half(value.w));
  }
  let rounded = (magnitude + vec4<u32>(0xfffu) + ((magnitude >> vec4<u32>(13u)) & vec4<u32>(1u)))
    & vec4<u32>(0xffffe000u);
  return bitcast<vec4<f32>>((bits & vec4<u32>(0x80000000u)) | rounded);
}
override MATMUL_FLAGS: u32 = 0u;
override MATMUL_ROWS: u32 = 32u;
override MATMUL_K: u32 = 32u;
override MATMUL_N: u32 = 32u;
override LAYOUT_WEIGHT_BYTE_OFFSET: u32 = 0u;
override LAYOUT_BIAS_BYTE_OFFSET: u32 = 0u;
override LAYOUT_WEIGHT_MATRIX_CHANNELS: u32 = 0u;
override LAYOUT_WEIGHT_COLUMN_OFFSET: u32 = 0u;
override LAYOUT_OUTPUT_MATRIX_CHANNELS: u32 = 0u;
override LAYOUT_OUTPUT_COLUMN_OFFSET: u32 = 0u;
override LAYOUT_INPUT_MATRIX_CHANNELS: u32 = 0u;
@group(0) @binding(5) var<storage, read> native_silu_table: array<u32>;
@group(0) @binding(6) var<storage, read> weight_metadata: array<vec2<f16>>;
fn load_residual(index: u32) -> f32 {
  if ((MATMUL_FLAGS & 262144u) != 0u) {
    return f32(weight_metadata[(residual_values[index / 4u] >> ((index % 4u) * 8u)) & 255u].x) * 0.25;
  }
  return f32(vec2<f16>(unpack2x16float(residual_values[index / 2u]))[index % 2u]);
}

fn publish_e4_code(value: f32) -> u32 {
  if (value != value) { return 0u; }
  let magnitude = min(abs(value), 448.0);
  if (magnitude == 0.0) { return 0u; }
  var code: u32;
  if (magnitude < 0.015625) {
    code = u32(round(magnitude * 512.0));
  } else {
    let bits = bitcast<u32>(magnitude);
    let rounded = (bits + 0x7ffffu + ((bits >> 20u) & 1u)) & 0xfff00000u;
    code = (rounded >> 20u) - 960u;
  }
  return code | select(0u, 128u, value < 0.0);
}
@group(0) @binding(7) var<storage, read_write> raw_values: array<f16>;
struct MatmulParams {
  rows: u32,
  input_channels: u32,
  output_channels: u32,
  weight_byte_offset: u32,
  bias_byte_offset: u32,
  flags: u32,
  weight_matrix_channels: u32,
  weight_column_offset: u32,
  output_matrix_channels: u32,
  output_column_offset: u32,
  input_matrix_channels: u32,
  batches: u32,
}

@group(0) @binding(0) var<storage, read> input_values: array<u32>;
@group(0) @binding(1) var<storage, read> packed_weights: array<u32>;
@group(0) @binding(2) var<storage, read_write> output_values: array<u32>;
@group(0) @binding(3) var<storage, read> residual_values: array<u32>;
@group(0) @binding(4) var<uniform> params: MatmulParams;

var<workgroup> tile_a: array<vec4<f16>, 256>;
var<workgroup> tile_b: array<vec4<f16>, 288>;
var<workgroup> tile_ea: array<vec4<f16>, 256>;
var<workgroup> tile_eb: array<vec4<f16>, 288>;

fn packed_byte(byte_offset: u32) -> u32 {
  let word = packed_weights[byte_offset >> 2u];
  return (word >> ((byte_offset & 3u) * 8u)) & 0xffu;
}

fn decode_e4m3(bits: u32) -> f32 {
  let negative = (bits & 0x80u) != 0u;
  let exponent = (bits >> 3u) & 0x0fu;
  let mantissa = bits & 0x07u;
  var value: f32;
  if (exponent == 0u) {
    value = f32(mantissa) * 0.001953125;
  } else if (exponent == 15u && mantissa == 7u) {
    value = 0.0;
  } else {
    value = (1.0 + f32(mantissa) * 0.125) * bitcast<f32>((exponent + 120u) << 23u);
  }
  return select(value, -value, negative);
}

fn packed_weight_index(k: u32, n: u32, output_channels: u32) -> u32 {
  let k_tile = k >> 5u;
  let k_in_tile = k & 31u;
  let n_tile = n >> 7u;
  let n_in_tile = n & 127u;
  let n_half = n_in_tile >> 6u;
  let n_group = (n_in_tile & 63u) >> 4u;
  let n_in_group = n_in_tile & 15u;
  let lane = ((n_in_group & 7u) << 2u) | ((k_in_tile & 15u) >> 2u);
  let byte_in_lane = ((n_in_group >> 3u) << 3u) | ((k_in_tile >> 4u) << 2u) | (k_in_tile & 3u);
  return k_tile * output_channels * 32u
    + n_tile * 4096u
    + n_half * 2048u
    + n_group * 512u
    + lane * 16u
    + byte_in_lane;
}

fn expert_interleaved_weight_index(k: u32, n: u32, experts: u32, expert: u32) -> u32 {
  let output_group = n >> 5u;
  let output_in_group = n & 31u;
  return output_group * experts * 1024u + expert * 1024u
    + packed_weight_index(k, output_in_group, 32u);
}

fn native_chained_input_index(k: u32) -> u32 {
  let base = k & ~31u;
  let within = k & 31u;
  let half = within & 16u;
  let quarter = within & 15u;
  return base + half + (quarter >> 2u) * 2u + (quarter & 1u)
    + select(0u, 8u, (quarter & 2u) != 0u);
}

fn native_inverse_chained_input_index(k: u32) -> u32 {
  let base = k & ~31u;
  let within = k & 31u;
  return base + (within & 17u) + ((within & 2u) << 1u)
    + ((within & 4u) << 1u) + ((within & 8u) >> 2u);
}

fn load_aux_half(channel: u32) -> f32 {
  let half_index = (LAYOUT_BIAS_BYTE_OFFSET >> 1u) + channel;
  let halves = unpack2x16float(packed_weights[half_index >> 1u]);
  return select(halves.x, halves.y, (half_index & 1u) != 0u);
}

fn round_accumulator(value: f32) -> f32 { return nr_round_half(value); }

// The network's cubic SiLU. Each step is one operation rounded once to half, and both the constants and the
// order they are applied in are part of the result rather than an implementation detail: see
// docs/numerics.md. The f32 twin in shaders/numerics.wgsl is checked against the same reference.
fn mp_cubic_silu(value: f32) -> f32 {
  let bounded = round_accumulator(clamp(value, -4.0, 4.0));
  let absolute = round_accumulator(abs(bounded));
  let inner = round_accumulator(-0.055908203125 * absolute + 0.447265625);
  let polynomial = round_accumulator(bounded * inner + 0.89453125);
  return round_accumulator(value * polynomial);
}

fn fp8_domain(value: f32) -> f32 {
  if (value != value) { return 0.0; }
  let magnitude = min(abs(value), 448.0);
  if (magnitude == 0.0) { return 0.0; }
  var quantized: f32;
  if (magnitude < 0.015625) {
    quantized = round(magnitude * 512.0) / 512.0;
  } else {
    let bits = bitcast<u32>(magnitude);
    quantized = bitcast<f32>((bits + 0x7ffffu + ((bits >> 20u) & 1u)) & 0xfff00000u);
  }
  return select(quantized, -quantized, value < 0.0);
}

// Bit-accurate Ada FP8 tensor-core arithmetic recovered independently by
// Microsoft's MMA-Sim model.  Ada's m16n8k32 FP8 instruction is two fused
// 16-product reductions.  Each reduction aligns its products and incoming
// FP16 accumulator to a shared exponent, truncates every aligned significand
// to 13 fractional bits, sums those fixed-point terms exactly, then rounds the
// result to FP16.  A scalar IEEE dot product does not reproduce this behavior.
fn normal_exponent(value: f32) -> i32 {
  return i32((bitcast<u32>(abs(value)) >> 23u) & 0xffu) - 127;
}

fn e4m3_exponent(value: f32) -> i32 {
  return max(normal_exponent(value), -6);
}

fn f16_exponent(value: f32) -> i32 {
  return max(normal_exponent(value), -14);
}




fn maximum_half_exponent(v: vec4<f16>) -> f16 {
  let pair = max(v.xy, v.zw);
  return max(pair.x, pair.y);
}
fn quad_fdpa_4_0(row: u32, column: u32, accumulator: vec4<f32>) -> vec4<f32> {
  var exponents = select(vec4<i32>(-21),
    max(vec4<i32>((bitcast<vec4<u32>>(abs(accumulator)) >> vec4<u32>(23u)) & vec4<u32>(255u))
      - vec4<i32>(127), vec4<i32>(-14)), accumulator != vec4<f32>(0.0));
  var maximum00: vec4<f16>;
  var maximum01: vec4<f16>;
  var maximum10: vec4<f16>;
  var maximum11: vec4<f16>;
  {
    let k = 0u;
    let a0 = tile_ea[row * 8u + k];
    let b0 = tile_eb[column * 9u + k];
    let b1 = tile_eb[(column + 1u) * 9u + k];
    let b2 = tile_eb[(column + 2u) * 9u + k];
    let b3 = tile_eb[(column + 3u) * 9u + k];
    maximum00 = a0 + b0;
    maximum01 = a0 + b1;
    maximum10 = a0 + b2;
    maximum11 = a0 + b3;
  }
  let maximum = vec4<f16>(maximum_half_exponent(maximum00), maximum_half_exponent(maximum01),
    maximum_half_exponent(maximum10), maximum_half_exponent(maximum11));
  exponents = max(exponents, vec4<i32>(maximum));
  let alignment = bitcast<vec4<f32>>(vec4<u32>(vec4<i32>(140) - exponents) << vec4<u32>(23u));
  var sums = trunc(accumulator * alignment);
  let product_alignment = bitcast<vec4<f32>>(vec4<u32>(vec4<i32>(136) - exponents) << vec4<u32>(23u));
  {
    let k = 0u;
    let a0 = tile_a[row * 8u + k];
    let b0 = tile_b[column * 9u + k];
    let b1 = tile_b[(column + 1u) * 9u + k];
    let b2 = tile_b[(column + 2u) * 9u + k];
    let b3 = tile_b[(column + 3u) * 9u + k];
    sums += trunc(vec4<f32>(vec4<f16>(a0.x)
      * vec4<f16>(b0.x, b1.x, b2.x, b3.x)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.y)
      * vec4<f16>(b0.y, b1.y, b2.y, b3.y)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.z)
      * vec4<f16>(b0.z, b1.z, b2.z, b3.z)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.w)
      * vec4<f16>(b0.w, b1.w, b2.w, b3.w)) * product_alignment);
  }
  let scale = bitcast<vec4<f32>>(vec4<u32>(exponents + vec4<i32>(114)) << vec4<u32>(23u));
  // FP8 products and the incoming half accumulator cannot produce a nonzero
  // result below the smallest half subnormal. Native publishes zero as +0.
  let rounded = nr_round_half4(sums * scale);
  return select(rounded, vec4<f32>(0.0), rounded == vec4<f32>(0.0));
}
fn quad_fdpa_4_4(row: u32, column: u32, accumulator: vec4<f32>) -> vec4<f32> {
  var exponents = select(vec4<i32>(-21),
    max(vec4<i32>((bitcast<vec4<u32>>(abs(accumulator)) >> vec4<u32>(23u)) & vec4<u32>(255u))
      - vec4<i32>(127), vec4<i32>(-14)), accumulator != vec4<f32>(0.0));
  var maximum00: vec4<f16>;
  var maximum01: vec4<f16>;
  var maximum10: vec4<f16>;
  var maximum11: vec4<f16>;
  {
    let k = 1u;
    let a0 = tile_ea[row * 8u + k];
    let b0 = tile_eb[column * 9u + k];
    let b1 = tile_eb[(column + 1u) * 9u + k];
    let b2 = tile_eb[(column + 2u) * 9u + k];
    let b3 = tile_eb[(column + 3u) * 9u + k];
    maximum00 = a0 + b0;
    maximum01 = a0 + b1;
    maximum10 = a0 + b2;
    maximum11 = a0 + b3;
  }
  let maximum = vec4<f16>(maximum_half_exponent(maximum00), maximum_half_exponent(maximum01),
    maximum_half_exponent(maximum10), maximum_half_exponent(maximum11));
  exponents = max(exponents, vec4<i32>(maximum));
  let alignment = bitcast<vec4<f32>>(vec4<u32>(vec4<i32>(140) - exponents) << vec4<u32>(23u));
  var sums = trunc(accumulator * alignment);
  let product_alignment = bitcast<vec4<f32>>(vec4<u32>(vec4<i32>(136) - exponents) << vec4<u32>(23u));
  {
    let k = 1u;
    let a0 = tile_a[row * 8u + k];
    let b0 = tile_b[column * 9u + k];
    let b1 = tile_b[(column + 1u) * 9u + k];
    let b2 = tile_b[(column + 2u) * 9u + k];
    let b3 = tile_b[(column + 3u) * 9u + k];
    sums += trunc(vec4<f32>(vec4<f16>(a0.x)
      * vec4<f16>(b0.x, b1.x, b2.x, b3.x)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.y)
      * vec4<f16>(b0.y, b1.y, b2.y, b3.y)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.z)
      * vec4<f16>(b0.z, b1.z, b2.z, b3.z)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.w)
      * vec4<f16>(b0.w, b1.w, b2.w, b3.w)) * product_alignment);
  }
  let scale = bitcast<vec4<f32>>(vec4<u32>(exponents + vec4<i32>(114)) << vec4<u32>(23u));
  // FP8 products and the incoming half accumulator cannot produce a nonzero
  // result below the smallest half subnormal. Native publishes zero as +0.
  let rounded = nr_round_half4(sums * scale);
  return select(rounded, vec4<f32>(0.0), rounded == vec4<f32>(0.0));
}
fn quad_fdpa_4_8(row: u32, column: u32, accumulator: vec4<f32>) -> vec4<f32> {
  var exponents = select(vec4<i32>(-21),
    max(vec4<i32>((bitcast<vec4<u32>>(abs(accumulator)) >> vec4<u32>(23u)) & vec4<u32>(255u))
      - vec4<i32>(127), vec4<i32>(-14)), accumulator != vec4<f32>(0.0));
  var maximum00: vec4<f16>;
  var maximum01: vec4<f16>;
  var maximum10: vec4<f16>;
  var maximum11: vec4<f16>;
  {
    let k = 2u;
    let a0 = tile_ea[row * 8u + k];
    let b0 = tile_eb[column * 9u + k];
    let b1 = tile_eb[(column + 1u) * 9u + k];
    let b2 = tile_eb[(column + 2u) * 9u + k];
    let b3 = tile_eb[(column + 3u) * 9u + k];
    maximum00 = a0 + b0;
    maximum01 = a0 + b1;
    maximum10 = a0 + b2;
    maximum11 = a0 + b3;
  }
  let maximum = vec4<f16>(maximum_half_exponent(maximum00), maximum_half_exponent(maximum01),
    maximum_half_exponent(maximum10), maximum_half_exponent(maximum11));
  exponents = max(exponents, vec4<i32>(maximum));
  let alignment = bitcast<vec4<f32>>(vec4<u32>(vec4<i32>(140) - exponents) << vec4<u32>(23u));
  var sums = trunc(accumulator * alignment);
  let product_alignment = bitcast<vec4<f32>>(vec4<u32>(vec4<i32>(136) - exponents) << vec4<u32>(23u));
  {
    let k = 2u;
    let a0 = tile_a[row * 8u + k];
    let b0 = tile_b[column * 9u + k];
    let b1 = tile_b[(column + 1u) * 9u + k];
    let b2 = tile_b[(column + 2u) * 9u + k];
    let b3 = tile_b[(column + 3u) * 9u + k];
    sums += trunc(vec4<f32>(vec4<f16>(a0.x)
      * vec4<f16>(b0.x, b1.x, b2.x, b3.x)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.y)
      * vec4<f16>(b0.y, b1.y, b2.y, b3.y)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.z)
      * vec4<f16>(b0.z, b1.z, b2.z, b3.z)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.w)
      * vec4<f16>(b0.w, b1.w, b2.w, b3.w)) * product_alignment);
  }
  let scale = bitcast<vec4<f32>>(vec4<u32>(exponents + vec4<i32>(114)) << vec4<u32>(23u));
  // FP8 products and the incoming half accumulator cannot produce a nonzero
  // result below the smallest half subnormal. Native publishes zero as +0.
  let rounded = nr_round_half4(sums * scale);
  return select(rounded, vec4<f32>(0.0), rounded == vec4<f32>(0.0));
}
fn quad_fdpa_4_12(row: u32, column: u32, accumulator: vec4<f32>) -> vec4<f32> {
  var exponents = select(vec4<i32>(-21),
    max(vec4<i32>((bitcast<vec4<u32>>(abs(accumulator)) >> vec4<u32>(23u)) & vec4<u32>(255u))
      - vec4<i32>(127), vec4<i32>(-14)), accumulator != vec4<f32>(0.0));
  var maximum00: vec4<f16>;
  var maximum01: vec4<f16>;
  var maximum10: vec4<f16>;
  var maximum11: vec4<f16>;
  {
    let k = 3u;
    let a0 = tile_ea[row * 8u + k];
    let b0 = tile_eb[column * 9u + k];
    let b1 = tile_eb[(column + 1u) * 9u + k];
    let b2 = tile_eb[(column + 2u) * 9u + k];
    let b3 = tile_eb[(column + 3u) * 9u + k];
    maximum00 = a0 + b0;
    maximum01 = a0 + b1;
    maximum10 = a0 + b2;
    maximum11 = a0 + b3;
  }
  let maximum = vec4<f16>(maximum_half_exponent(maximum00), maximum_half_exponent(maximum01),
    maximum_half_exponent(maximum10), maximum_half_exponent(maximum11));
  exponents = max(exponents, vec4<i32>(maximum));
  let alignment = bitcast<vec4<f32>>(vec4<u32>(vec4<i32>(140) - exponents) << vec4<u32>(23u));
  var sums = trunc(accumulator * alignment);
  let product_alignment = bitcast<vec4<f32>>(vec4<u32>(vec4<i32>(136) - exponents) << vec4<u32>(23u));
  {
    let k = 3u;
    let a0 = tile_a[row * 8u + k];
    let b0 = tile_b[column * 9u + k];
    let b1 = tile_b[(column + 1u) * 9u + k];
    let b2 = tile_b[(column + 2u) * 9u + k];
    let b3 = tile_b[(column + 3u) * 9u + k];
    sums += trunc(vec4<f32>(vec4<f16>(a0.x)
      * vec4<f16>(b0.x, b1.x, b2.x, b3.x)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.y)
      * vec4<f16>(b0.y, b1.y, b2.y, b3.y)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.z)
      * vec4<f16>(b0.z, b1.z, b2.z, b3.z)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.w)
      * vec4<f16>(b0.w, b1.w, b2.w, b3.w)) * product_alignment);
  }
  let scale = bitcast<vec4<f32>>(vec4<u32>(exponents + vec4<i32>(114)) << vec4<u32>(23u));
  // FP8 products and the incoming half accumulator cannot produce a nonzero
  // result below the smallest half subnormal. Native publishes zero as +0.
  let rounded = nr_round_half4(sums * scale);
  return select(rounded, vec4<f32>(0.0), rounded == vec4<f32>(0.0));
}
fn quad_fdpa_4_16(row: u32, column: u32, accumulator: vec4<f32>) -> vec4<f32> {
  var exponents = select(vec4<i32>(-21),
    max(vec4<i32>((bitcast<vec4<u32>>(abs(accumulator)) >> vec4<u32>(23u)) & vec4<u32>(255u))
      - vec4<i32>(127), vec4<i32>(-14)), accumulator != vec4<f32>(0.0));
  var maximum00: vec4<f16>;
  var maximum01: vec4<f16>;
  var maximum10: vec4<f16>;
  var maximum11: vec4<f16>;
  {
    let k = 4u;
    let a0 = tile_ea[row * 8u + k];
    let b0 = tile_eb[column * 9u + k];
    let b1 = tile_eb[(column + 1u) * 9u + k];
    let b2 = tile_eb[(column + 2u) * 9u + k];
    let b3 = tile_eb[(column + 3u) * 9u + k];
    maximum00 = a0 + b0;
    maximum01 = a0 + b1;
    maximum10 = a0 + b2;
    maximum11 = a0 + b3;
  }
  let maximum = vec4<f16>(maximum_half_exponent(maximum00), maximum_half_exponent(maximum01),
    maximum_half_exponent(maximum10), maximum_half_exponent(maximum11));
  exponents = max(exponents, vec4<i32>(maximum));
  let alignment = bitcast<vec4<f32>>(vec4<u32>(vec4<i32>(140) - exponents) << vec4<u32>(23u));
  var sums = trunc(accumulator * alignment);
  let product_alignment = bitcast<vec4<f32>>(vec4<u32>(vec4<i32>(136) - exponents) << vec4<u32>(23u));
  {
    let k = 4u;
    let a0 = tile_a[row * 8u + k];
    let b0 = tile_b[column * 9u + k];
    let b1 = tile_b[(column + 1u) * 9u + k];
    let b2 = tile_b[(column + 2u) * 9u + k];
    let b3 = tile_b[(column + 3u) * 9u + k];
    sums += trunc(vec4<f32>(vec4<f16>(a0.x)
      * vec4<f16>(b0.x, b1.x, b2.x, b3.x)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.y)
      * vec4<f16>(b0.y, b1.y, b2.y, b3.y)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.z)
      * vec4<f16>(b0.z, b1.z, b2.z, b3.z)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.w)
      * vec4<f16>(b0.w, b1.w, b2.w, b3.w)) * product_alignment);
  }
  let scale = bitcast<vec4<f32>>(vec4<u32>(exponents + vec4<i32>(114)) << vec4<u32>(23u));
  // FP8 products and the incoming half accumulator cannot produce a nonzero
  // result below the smallest half subnormal. Native publishes zero as +0.
  let rounded = nr_round_half4(sums * scale);
  return select(rounded, vec4<f32>(0.0), rounded == vec4<f32>(0.0));
}
fn quad_fdpa_4_20(row: u32, column: u32, accumulator: vec4<f32>) -> vec4<f32> {
  var exponents = select(vec4<i32>(-21),
    max(vec4<i32>((bitcast<vec4<u32>>(abs(accumulator)) >> vec4<u32>(23u)) & vec4<u32>(255u))
      - vec4<i32>(127), vec4<i32>(-14)), accumulator != vec4<f32>(0.0));
  var maximum00: vec4<f16>;
  var maximum01: vec4<f16>;
  var maximum10: vec4<f16>;
  var maximum11: vec4<f16>;
  {
    let k = 5u;
    let a0 = tile_ea[row * 8u + k];
    let b0 = tile_eb[column * 9u + k];
    let b1 = tile_eb[(column + 1u) * 9u + k];
    let b2 = tile_eb[(column + 2u) * 9u + k];
    let b3 = tile_eb[(column + 3u) * 9u + k];
    maximum00 = a0 + b0;
    maximum01 = a0 + b1;
    maximum10 = a0 + b2;
    maximum11 = a0 + b3;
  }
  let maximum = vec4<f16>(maximum_half_exponent(maximum00), maximum_half_exponent(maximum01),
    maximum_half_exponent(maximum10), maximum_half_exponent(maximum11));
  exponents = max(exponents, vec4<i32>(maximum));
  let alignment = bitcast<vec4<f32>>(vec4<u32>(vec4<i32>(140) - exponents) << vec4<u32>(23u));
  var sums = trunc(accumulator * alignment);
  let product_alignment = bitcast<vec4<f32>>(vec4<u32>(vec4<i32>(136) - exponents) << vec4<u32>(23u));
  {
    let k = 5u;
    let a0 = tile_a[row * 8u + k];
    let b0 = tile_b[column * 9u + k];
    let b1 = tile_b[(column + 1u) * 9u + k];
    let b2 = tile_b[(column + 2u) * 9u + k];
    let b3 = tile_b[(column + 3u) * 9u + k];
    sums += trunc(vec4<f32>(vec4<f16>(a0.x)
      * vec4<f16>(b0.x, b1.x, b2.x, b3.x)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.y)
      * vec4<f16>(b0.y, b1.y, b2.y, b3.y)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.z)
      * vec4<f16>(b0.z, b1.z, b2.z, b3.z)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.w)
      * vec4<f16>(b0.w, b1.w, b2.w, b3.w)) * product_alignment);
  }
  let scale = bitcast<vec4<f32>>(vec4<u32>(exponents + vec4<i32>(114)) << vec4<u32>(23u));
  // FP8 products and the incoming half accumulator cannot produce a nonzero
  // result below the smallest half subnormal. Native publishes zero as +0.
  let rounded = nr_round_half4(sums * scale);
  return select(rounded, vec4<f32>(0.0), rounded == vec4<f32>(0.0));
}
fn quad_fdpa_4_24(row: u32, column: u32, accumulator: vec4<f32>) -> vec4<f32> {
  var exponents = select(vec4<i32>(-21),
    max(vec4<i32>((bitcast<vec4<u32>>(abs(accumulator)) >> vec4<u32>(23u)) & vec4<u32>(255u))
      - vec4<i32>(127), vec4<i32>(-14)), accumulator != vec4<f32>(0.0));
  var maximum00: vec4<f16>;
  var maximum01: vec4<f16>;
  var maximum10: vec4<f16>;
  var maximum11: vec4<f16>;
  {
    let k = 6u;
    let a0 = tile_ea[row * 8u + k];
    let b0 = tile_eb[column * 9u + k];
    let b1 = tile_eb[(column + 1u) * 9u + k];
    let b2 = tile_eb[(column + 2u) * 9u + k];
    let b3 = tile_eb[(column + 3u) * 9u + k];
    maximum00 = a0 + b0;
    maximum01 = a0 + b1;
    maximum10 = a0 + b2;
    maximum11 = a0 + b3;
  }
  let maximum = vec4<f16>(maximum_half_exponent(maximum00), maximum_half_exponent(maximum01),
    maximum_half_exponent(maximum10), maximum_half_exponent(maximum11));
  exponents = max(exponents, vec4<i32>(maximum));
  let alignment = bitcast<vec4<f32>>(vec4<u32>(vec4<i32>(140) - exponents) << vec4<u32>(23u));
  var sums = trunc(accumulator * alignment);
  let product_alignment = bitcast<vec4<f32>>(vec4<u32>(vec4<i32>(136) - exponents) << vec4<u32>(23u));
  {
    let k = 6u;
    let a0 = tile_a[row * 8u + k];
    let b0 = tile_b[column * 9u + k];
    let b1 = tile_b[(column + 1u) * 9u + k];
    let b2 = tile_b[(column + 2u) * 9u + k];
    let b3 = tile_b[(column + 3u) * 9u + k];
    sums += trunc(vec4<f32>(vec4<f16>(a0.x)
      * vec4<f16>(b0.x, b1.x, b2.x, b3.x)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.y)
      * vec4<f16>(b0.y, b1.y, b2.y, b3.y)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.z)
      * vec4<f16>(b0.z, b1.z, b2.z, b3.z)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.w)
      * vec4<f16>(b0.w, b1.w, b2.w, b3.w)) * product_alignment);
  }
  let scale = bitcast<vec4<f32>>(vec4<u32>(exponents + vec4<i32>(114)) << vec4<u32>(23u));
  // FP8 products and the incoming half accumulator cannot produce a nonzero
  // result below the smallest half subnormal. Native publishes zero as +0.
  let rounded = nr_round_half4(sums * scale);
  return select(rounded, vec4<f32>(0.0), rounded == vec4<f32>(0.0));
}
fn quad_fdpa_4_28(row: u32, column: u32, accumulator: vec4<f32>) -> vec4<f32> {
  var exponents = select(vec4<i32>(-21),
    max(vec4<i32>((bitcast<vec4<u32>>(abs(accumulator)) >> vec4<u32>(23u)) & vec4<u32>(255u))
      - vec4<i32>(127), vec4<i32>(-14)), accumulator != vec4<f32>(0.0));
  var maximum00: vec4<f16>;
  var maximum01: vec4<f16>;
  var maximum10: vec4<f16>;
  var maximum11: vec4<f16>;
  {
    let k = 7u;
    let a0 = tile_ea[row * 8u + k];
    let b0 = tile_eb[column * 9u + k];
    let b1 = tile_eb[(column + 1u) * 9u + k];
    let b2 = tile_eb[(column + 2u) * 9u + k];
    let b3 = tile_eb[(column + 3u) * 9u + k];
    maximum00 = a0 + b0;
    maximum01 = a0 + b1;
    maximum10 = a0 + b2;
    maximum11 = a0 + b3;
  }
  let maximum = vec4<f16>(maximum_half_exponent(maximum00), maximum_half_exponent(maximum01),
    maximum_half_exponent(maximum10), maximum_half_exponent(maximum11));
  exponents = max(exponents, vec4<i32>(maximum));
  let alignment = bitcast<vec4<f32>>(vec4<u32>(vec4<i32>(140) - exponents) << vec4<u32>(23u));
  var sums = trunc(accumulator * alignment);
  let product_alignment = bitcast<vec4<f32>>(vec4<u32>(vec4<i32>(136) - exponents) << vec4<u32>(23u));
  {
    let k = 7u;
    let a0 = tile_a[row * 8u + k];
    let b0 = tile_b[column * 9u + k];
    let b1 = tile_b[(column + 1u) * 9u + k];
    let b2 = tile_b[(column + 2u) * 9u + k];
    let b3 = tile_b[(column + 3u) * 9u + k];
    sums += trunc(vec4<f32>(vec4<f16>(a0.x)
      * vec4<f16>(b0.x, b1.x, b2.x, b3.x)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.y)
      * vec4<f16>(b0.y, b1.y, b2.y, b3.y)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.z)
      * vec4<f16>(b0.z, b1.z, b2.z, b3.z)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.w)
      * vec4<f16>(b0.w, b1.w, b2.w, b3.w)) * product_alignment);
  }
  let scale = bitcast<vec4<f32>>(vec4<u32>(exponents + vec4<i32>(114)) << vec4<u32>(23u));
  // FP8 products and the incoming half accumulator cannot produce a nonzero
  // result below the smallest half subnormal. Native publishes zero as +0.
  let rounded = nr_round_half4(sums * scale);
  return select(rounded, vec4<f32>(0.0), rounded == vec4<f32>(0.0));
}
fn quad_fdpa_8_0(row: u32, column: u32, accumulator: vec4<f32>) -> vec4<f32> {
  var exponents = select(vec4<i32>(-21),
    max(vec4<i32>((bitcast<vec4<u32>>(abs(accumulator)) >> vec4<u32>(23u)) & vec4<u32>(255u))
      - vec4<i32>(127), vec4<i32>(-14)), accumulator != vec4<f32>(0.0));
  var maximum00: vec4<f16>;
  var maximum01: vec4<f16>;
  var maximum10: vec4<f16>;
  var maximum11: vec4<f16>;
  {
    let k = 0u;
    let a0 = tile_ea[row * 8u + k];
    let b0 = tile_eb[column * 9u + k];
    let b1 = tile_eb[(column + 1u) * 9u + k];
    let b2 = tile_eb[(column + 2u) * 9u + k];
    let b3 = tile_eb[(column + 3u) * 9u + k];
    maximum00 = a0 + b0;
    maximum01 = a0 + b1;
    maximum10 = a0 + b2;
    maximum11 = a0 + b3;
  }
  {
    let k = 1u;
    let a0 = tile_ea[row * 8u + k];
    let b0 = tile_eb[column * 9u + k];
    let b1 = tile_eb[(column + 1u) * 9u + k];
    let b2 = tile_eb[(column + 2u) * 9u + k];
    let b3 = tile_eb[(column + 3u) * 9u + k];
    maximum00 = max(maximum00, a0 + b0);
    maximum01 = max(maximum01, a0 + b1);
    maximum10 = max(maximum10, a0 + b2);
    maximum11 = max(maximum11, a0 + b3);
  }
  let maximum = vec4<f16>(maximum_half_exponent(maximum00), maximum_half_exponent(maximum01),
    maximum_half_exponent(maximum10), maximum_half_exponent(maximum11));
  exponents = max(exponents, vec4<i32>(maximum));
  let alignment = bitcast<vec4<f32>>(vec4<u32>(vec4<i32>(140) - exponents) << vec4<u32>(23u));
  var sums = trunc(accumulator * alignment);
  let product_alignment = bitcast<vec4<f32>>(vec4<u32>(vec4<i32>(136) - exponents) << vec4<u32>(23u));
  {
    let k = 0u;
    let a0 = tile_a[row * 8u + k];
    let b0 = tile_b[column * 9u + k];
    let b1 = tile_b[(column + 1u) * 9u + k];
    let b2 = tile_b[(column + 2u) * 9u + k];
    let b3 = tile_b[(column + 3u) * 9u + k];
    sums += trunc(vec4<f32>(vec4<f16>(a0.x)
      * vec4<f16>(b0.x, b1.x, b2.x, b3.x)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.y)
      * vec4<f16>(b0.y, b1.y, b2.y, b3.y)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.z)
      * vec4<f16>(b0.z, b1.z, b2.z, b3.z)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.w)
      * vec4<f16>(b0.w, b1.w, b2.w, b3.w)) * product_alignment);
  }
  {
    let k = 1u;
    let a0 = tile_a[row * 8u + k];
    let b0 = tile_b[column * 9u + k];
    let b1 = tile_b[(column + 1u) * 9u + k];
    let b2 = tile_b[(column + 2u) * 9u + k];
    let b3 = tile_b[(column + 3u) * 9u + k];
    sums += trunc(vec4<f32>(vec4<f16>(a0.x)
      * vec4<f16>(b0.x, b1.x, b2.x, b3.x)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.y)
      * vec4<f16>(b0.y, b1.y, b2.y, b3.y)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.z)
      * vec4<f16>(b0.z, b1.z, b2.z, b3.z)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.w)
      * vec4<f16>(b0.w, b1.w, b2.w, b3.w)) * product_alignment);
  }
  let scale = bitcast<vec4<f32>>(vec4<u32>(exponents + vec4<i32>(114)) << vec4<u32>(23u));
  // FP8 products and the incoming half accumulator cannot produce a nonzero
  // result below the smallest half subnormal. Native publishes zero as +0.
  let rounded = nr_round_half4(sums * scale);
  return select(rounded, vec4<f32>(0.0), rounded == vec4<f32>(0.0));
}
fn quad_fdpa_8_8(row: u32, column: u32, accumulator: vec4<f32>) -> vec4<f32> {
  var exponents = select(vec4<i32>(-21),
    max(vec4<i32>((bitcast<vec4<u32>>(abs(accumulator)) >> vec4<u32>(23u)) & vec4<u32>(255u))
      - vec4<i32>(127), vec4<i32>(-14)), accumulator != vec4<f32>(0.0));
  var maximum00: vec4<f16>;
  var maximum01: vec4<f16>;
  var maximum10: vec4<f16>;
  var maximum11: vec4<f16>;
  {
    let k = 2u;
    let a0 = tile_ea[row * 8u + k];
    let b0 = tile_eb[column * 9u + k];
    let b1 = tile_eb[(column + 1u) * 9u + k];
    let b2 = tile_eb[(column + 2u) * 9u + k];
    let b3 = tile_eb[(column + 3u) * 9u + k];
    maximum00 = a0 + b0;
    maximum01 = a0 + b1;
    maximum10 = a0 + b2;
    maximum11 = a0 + b3;
  }
  {
    let k = 3u;
    let a0 = tile_ea[row * 8u + k];
    let b0 = tile_eb[column * 9u + k];
    let b1 = tile_eb[(column + 1u) * 9u + k];
    let b2 = tile_eb[(column + 2u) * 9u + k];
    let b3 = tile_eb[(column + 3u) * 9u + k];
    maximum00 = max(maximum00, a0 + b0);
    maximum01 = max(maximum01, a0 + b1);
    maximum10 = max(maximum10, a0 + b2);
    maximum11 = max(maximum11, a0 + b3);
  }
  let maximum = vec4<f16>(maximum_half_exponent(maximum00), maximum_half_exponent(maximum01),
    maximum_half_exponent(maximum10), maximum_half_exponent(maximum11));
  exponents = max(exponents, vec4<i32>(maximum));
  let alignment = bitcast<vec4<f32>>(vec4<u32>(vec4<i32>(140) - exponents) << vec4<u32>(23u));
  var sums = trunc(accumulator * alignment);
  let product_alignment = bitcast<vec4<f32>>(vec4<u32>(vec4<i32>(136) - exponents) << vec4<u32>(23u));
  {
    let k = 2u;
    let a0 = tile_a[row * 8u + k];
    let b0 = tile_b[column * 9u + k];
    let b1 = tile_b[(column + 1u) * 9u + k];
    let b2 = tile_b[(column + 2u) * 9u + k];
    let b3 = tile_b[(column + 3u) * 9u + k];
    sums += trunc(vec4<f32>(vec4<f16>(a0.x)
      * vec4<f16>(b0.x, b1.x, b2.x, b3.x)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.y)
      * vec4<f16>(b0.y, b1.y, b2.y, b3.y)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.z)
      * vec4<f16>(b0.z, b1.z, b2.z, b3.z)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.w)
      * vec4<f16>(b0.w, b1.w, b2.w, b3.w)) * product_alignment);
  }
  {
    let k = 3u;
    let a0 = tile_a[row * 8u + k];
    let b0 = tile_b[column * 9u + k];
    let b1 = tile_b[(column + 1u) * 9u + k];
    let b2 = tile_b[(column + 2u) * 9u + k];
    let b3 = tile_b[(column + 3u) * 9u + k];
    sums += trunc(vec4<f32>(vec4<f16>(a0.x)
      * vec4<f16>(b0.x, b1.x, b2.x, b3.x)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.y)
      * vec4<f16>(b0.y, b1.y, b2.y, b3.y)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.z)
      * vec4<f16>(b0.z, b1.z, b2.z, b3.z)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.w)
      * vec4<f16>(b0.w, b1.w, b2.w, b3.w)) * product_alignment);
  }
  let scale = bitcast<vec4<f32>>(vec4<u32>(exponents + vec4<i32>(114)) << vec4<u32>(23u));
  // FP8 products and the incoming half accumulator cannot produce a nonzero
  // result below the smallest half subnormal. Native publishes zero as +0.
  let rounded = nr_round_half4(sums * scale);
  return select(rounded, vec4<f32>(0.0), rounded == vec4<f32>(0.0));
}
fn quad_fdpa_8_16(row: u32, column: u32, accumulator: vec4<f32>) -> vec4<f32> {
  var exponents = select(vec4<i32>(-21),
    max(vec4<i32>((bitcast<vec4<u32>>(abs(accumulator)) >> vec4<u32>(23u)) & vec4<u32>(255u))
      - vec4<i32>(127), vec4<i32>(-14)), accumulator != vec4<f32>(0.0));
  var maximum00: vec4<f16>;
  var maximum01: vec4<f16>;
  var maximum10: vec4<f16>;
  var maximum11: vec4<f16>;
  {
    let k = 4u;
    let a0 = tile_ea[row * 8u + k];
    let b0 = tile_eb[column * 9u + k];
    let b1 = tile_eb[(column + 1u) * 9u + k];
    let b2 = tile_eb[(column + 2u) * 9u + k];
    let b3 = tile_eb[(column + 3u) * 9u + k];
    maximum00 = a0 + b0;
    maximum01 = a0 + b1;
    maximum10 = a0 + b2;
    maximum11 = a0 + b3;
  }
  {
    let k = 5u;
    let a0 = tile_ea[row * 8u + k];
    let b0 = tile_eb[column * 9u + k];
    let b1 = tile_eb[(column + 1u) * 9u + k];
    let b2 = tile_eb[(column + 2u) * 9u + k];
    let b3 = tile_eb[(column + 3u) * 9u + k];
    maximum00 = max(maximum00, a0 + b0);
    maximum01 = max(maximum01, a0 + b1);
    maximum10 = max(maximum10, a0 + b2);
    maximum11 = max(maximum11, a0 + b3);
  }
  let maximum = vec4<f16>(maximum_half_exponent(maximum00), maximum_half_exponent(maximum01),
    maximum_half_exponent(maximum10), maximum_half_exponent(maximum11));
  exponents = max(exponents, vec4<i32>(maximum));
  let alignment = bitcast<vec4<f32>>(vec4<u32>(vec4<i32>(140) - exponents) << vec4<u32>(23u));
  var sums = trunc(accumulator * alignment);
  let product_alignment = bitcast<vec4<f32>>(vec4<u32>(vec4<i32>(136) - exponents) << vec4<u32>(23u));
  {
    let k = 4u;
    let a0 = tile_a[row * 8u + k];
    let b0 = tile_b[column * 9u + k];
    let b1 = tile_b[(column + 1u) * 9u + k];
    let b2 = tile_b[(column + 2u) * 9u + k];
    let b3 = tile_b[(column + 3u) * 9u + k];
    sums += trunc(vec4<f32>(vec4<f16>(a0.x)
      * vec4<f16>(b0.x, b1.x, b2.x, b3.x)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.y)
      * vec4<f16>(b0.y, b1.y, b2.y, b3.y)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.z)
      * vec4<f16>(b0.z, b1.z, b2.z, b3.z)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.w)
      * vec4<f16>(b0.w, b1.w, b2.w, b3.w)) * product_alignment);
  }
  {
    let k = 5u;
    let a0 = tile_a[row * 8u + k];
    let b0 = tile_b[column * 9u + k];
    let b1 = tile_b[(column + 1u) * 9u + k];
    let b2 = tile_b[(column + 2u) * 9u + k];
    let b3 = tile_b[(column + 3u) * 9u + k];
    sums += trunc(vec4<f32>(vec4<f16>(a0.x)
      * vec4<f16>(b0.x, b1.x, b2.x, b3.x)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.y)
      * vec4<f16>(b0.y, b1.y, b2.y, b3.y)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.z)
      * vec4<f16>(b0.z, b1.z, b2.z, b3.z)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.w)
      * vec4<f16>(b0.w, b1.w, b2.w, b3.w)) * product_alignment);
  }
  let scale = bitcast<vec4<f32>>(vec4<u32>(exponents + vec4<i32>(114)) << vec4<u32>(23u));
  // FP8 products and the incoming half accumulator cannot produce a nonzero
  // result below the smallest half subnormal. Native publishes zero as +0.
  let rounded = nr_round_half4(sums * scale);
  return select(rounded, vec4<f32>(0.0), rounded == vec4<f32>(0.0));
}
fn quad_fdpa_8_24(row: u32, column: u32, accumulator: vec4<f32>) -> vec4<f32> {
  var exponents = select(vec4<i32>(-21),
    max(vec4<i32>((bitcast<vec4<u32>>(abs(accumulator)) >> vec4<u32>(23u)) & vec4<u32>(255u))
      - vec4<i32>(127), vec4<i32>(-14)), accumulator != vec4<f32>(0.0));
  var maximum00: vec4<f16>;
  var maximum01: vec4<f16>;
  var maximum10: vec4<f16>;
  var maximum11: vec4<f16>;
  {
    let k = 6u;
    let a0 = tile_ea[row * 8u + k];
    let b0 = tile_eb[column * 9u + k];
    let b1 = tile_eb[(column + 1u) * 9u + k];
    let b2 = tile_eb[(column + 2u) * 9u + k];
    let b3 = tile_eb[(column + 3u) * 9u + k];
    maximum00 = a0 + b0;
    maximum01 = a0 + b1;
    maximum10 = a0 + b2;
    maximum11 = a0 + b3;
  }
  {
    let k = 7u;
    let a0 = tile_ea[row * 8u + k];
    let b0 = tile_eb[column * 9u + k];
    let b1 = tile_eb[(column + 1u) * 9u + k];
    let b2 = tile_eb[(column + 2u) * 9u + k];
    let b3 = tile_eb[(column + 3u) * 9u + k];
    maximum00 = max(maximum00, a0 + b0);
    maximum01 = max(maximum01, a0 + b1);
    maximum10 = max(maximum10, a0 + b2);
    maximum11 = max(maximum11, a0 + b3);
  }
  let maximum = vec4<f16>(maximum_half_exponent(maximum00), maximum_half_exponent(maximum01),
    maximum_half_exponent(maximum10), maximum_half_exponent(maximum11));
  exponents = max(exponents, vec4<i32>(maximum));
  let alignment = bitcast<vec4<f32>>(vec4<u32>(vec4<i32>(140) - exponents) << vec4<u32>(23u));
  var sums = trunc(accumulator * alignment);
  let product_alignment = bitcast<vec4<f32>>(vec4<u32>(vec4<i32>(136) - exponents) << vec4<u32>(23u));
  {
    let k = 6u;
    let a0 = tile_a[row * 8u + k];
    let b0 = tile_b[column * 9u + k];
    let b1 = tile_b[(column + 1u) * 9u + k];
    let b2 = tile_b[(column + 2u) * 9u + k];
    let b3 = tile_b[(column + 3u) * 9u + k];
    sums += trunc(vec4<f32>(vec4<f16>(a0.x)
      * vec4<f16>(b0.x, b1.x, b2.x, b3.x)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.y)
      * vec4<f16>(b0.y, b1.y, b2.y, b3.y)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.z)
      * vec4<f16>(b0.z, b1.z, b2.z, b3.z)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.w)
      * vec4<f16>(b0.w, b1.w, b2.w, b3.w)) * product_alignment);
  }
  {
    let k = 7u;
    let a0 = tile_a[row * 8u + k];
    let b0 = tile_b[column * 9u + k];
    let b1 = tile_b[(column + 1u) * 9u + k];
    let b2 = tile_b[(column + 2u) * 9u + k];
    let b3 = tile_b[(column + 3u) * 9u + k];
    sums += trunc(vec4<f32>(vec4<f16>(a0.x)
      * vec4<f16>(b0.x, b1.x, b2.x, b3.x)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.y)
      * vec4<f16>(b0.y, b1.y, b2.y, b3.y)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.z)
      * vec4<f16>(b0.z, b1.z, b2.z, b3.z)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.w)
      * vec4<f16>(b0.w, b1.w, b2.w, b3.w)) * product_alignment);
  }
  let scale = bitcast<vec4<f32>>(vec4<u32>(exponents + vec4<i32>(114)) << vec4<u32>(23u));
  // FP8 products and the incoming half accumulator cannot produce a nonzero
  // result below the smallest half subnormal. Native publishes zero as +0.
  let rounded = nr_round_half4(sums * scale);
  return select(rounded, vec4<f32>(0.0), rounded == vec4<f32>(0.0));
}
fn quad_fdpa_16_0(row: u32, column: u32, accumulator: vec4<f32>) -> vec4<f32> {
  var exponents = select(vec4<i32>(-21),
    max(vec4<i32>((bitcast<vec4<u32>>(abs(accumulator)) >> vec4<u32>(23u)) & vec4<u32>(255u))
      - vec4<i32>(127), vec4<i32>(-14)), accumulator != vec4<f32>(0.0));
  var maximum00: vec4<f16>;
  var maximum01: vec4<f16>;
  var maximum10: vec4<f16>;
  var maximum11: vec4<f16>;
  {
    let k = 0u;
    let a0 = tile_ea[row * 8u + k];
    let b0 = tile_eb[column * 9u + k];
    let b1 = tile_eb[(column + 1u) * 9u + k];
    let b2 = tile_eb[(column + 2u) * 9u + k];
    let b3 = tile_eb[(column + 3u) * 9u + k];
    maximum00 = a0 + b0;
    maximum01 = a0 + b1;
    maximum10 = a0 + b2;
    maximum11 = a0 + b3;
  }
  {
    let k = 1u;
    let a0 = tile_ea[row * 8u + k];
    let b0 = tile_eb[column * 9u + k];
    let b1 = tile_eb[(column + 1u) * 9u + k];
    let b2 = tile_eb[(column + 2u) * 9u + k];
    let b3 = tile_eb[(column + 3u) * 9u + k];
    maximum00 = max(maximum00, a0 + b0);
    maximum01 = max(maximum01, a0 + b1);
    maximum10 = max(maximum10, a0 + b2);
    maximum11 = max(maximum11, a0 + b3);
  }
  {
    let k = 2u;
    let a0 = tile_ea[row * 8u + k];
    let b0 = tile_eb[column * 9u + k];
    let b1 = tile_eb[(column + 1u) * 9u + k];
    let b2 = tile_eb[(column + 2u) * 9u + k];
    let b3 = tile_eb[(column + 3u) * 9u + k];
    maximum00 = max(maximum00, a0 + b0);
    maximum01 = max(maximum01, a0 + b1);
    maximum10 = max(maximum10, a0 + b2);
    maximum11 = max(maximum11, a0 + b3);
  }
  {
    let k = 3u;
    let a0 = tile_ea[row * 8u + k];
    let b0 = tile_eb[column * 9u + k];
    let b1 = tile_eb[(column + 1u) * 9u + k];
    let b2 = tile_eb[(column + 2u) * 9u + k];
    let b3 = tile_eb[(column + 3u) * 9u + k];
    maximum00 = max(maximum00, a0 + b0);
    maximum01 = max(maximum01, a0 + b1);
    maximum10 = max(maximum10, a0 + b2);
    maximum11 = max(maximum11, a0 + b3);
  }
  let maximum = vec4<f16>(maximum_half_exponent(maximum00), maximum_half_exponent(maximum01),
    maximum_half_exponent(maximum10), maximum_half_exponent(maximum11));
  exponents = max(exponents, vec4<i32>(maximum));
  let alignment = bitcast<vec4<f32>>(vec4<u32>(vec4<i32>(140) - exponents) << vec4<u32>(23u));
  var sums = trunc(accumulator * alignment);
  let product_alignment = bitcast<vec4<f32>>(vec4<u32>(vec4<i32>(136) - exponents) << vec4<u32>(23u));
  {
    let k = 0u;
    let a0 = tile_a[row * 8u + k];
    let b0 = tile_b[column * 9u + k];
    let b1 = tile_b[(column + 1u) * 9u + k];
    let b2 = tile_b[(column + 2u) * 9u + k];
    let b3 = tile_b[(column + 3u) * 9u + k];
    sums += trunc(vec4<f32>(vec4<f16>(a0.x)
      * vec4<f16>(b0.x, b1.x, b2.x, b3.x)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.y)
      * vec4<f16>(b0.y, b1.y, b2.y, b3.y)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.z)
      * vec4<f16>(b0.z, b1.z, b2.z, b3.z)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.w)
      * vec4<f16>(b0.w, b1.w, b2.w, b3.w)) * product_alignment);
  }
  {
    let k = 1u;
    let a0 = tile_a[row * 8u + k];
    let b0 = tile_b[column * 9u + k];
    let b1 = tile_b[(column + 1u) * 9u + k];
    let b2 = tile_b[(column + 2u) * 9u + k];
    let b3 = tile_b[(column + 3u) * 9u + k];
    sums += trunc(vec4<f32>(vec4<f16>(a0.x)
      * vec4<f16>(b0.x, b1.x, b2.x, b3.x)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.y)
      * vec4<f16>(b0.y, b1.y, b2.y, b3.y)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.z)
      * vec4<f16>(b0.z, b1.z, b2.z, b3.z)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.w)
      * vec4<f16>(b0.w, b1.w, b2.w, b3.w)) * product_alignment);
  }
  {
    let k = 2u;
    let a0 = tile_a[row * 8u + k];
    let b0 = tile_b[column * 9u + k];
    let b1 = tile_b[(column + 1u) * 9u + k];
    let b2 = tile_b[(column + 2u) * 9u + k];
    let b3 = tile_b[(column + 3u) * 9u + k];
    sums += trunc(vec4<f32>(vec4<f16>(a0.x)
      * vec4<f16>(b0.x, b1.x, b2.x, b3.x)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.y)
      * vec4<f16>(b0.y, b1.y, b2.y, b3.y)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.z)
      * vec4<f16>(b0.z, b1.z, b2.z, b3.z)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.w)
      * vec4<f16>(b0.w, b1.w, b2.w, b3.w)) * product_alignment);
  }
  {
    let k = 3u;
    let a0 = tile_a[row * 8u + k];
    let b0 = tile_b[column * 9u + k];
    let b1 = tile_b[(column + 1u) * 9u + k];
    let b2 = tile_b[(column + 2u) * 9u + k];
    let b3 = tile_b[(column + 3u) * 9u + k];
    sums += trunc(vec4<f32>(vec4<f16>(a0.x)
      * vec4<f16>(b0.x, b1.x, b2.x, b3.x)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.y)
      * vec4<f16>(b0.y, b1.y, b2.y, b3.y)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.z)
      * vec4<f16>(b0.z, b1.z, b2.z, b3.z)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.w)
      * vec4<f16>(b0.w, b1.w, b2.w, b3.w)) * product_alignment);
  }
  let scale = bitcast<vec4<f32>>(vec4<u32>(exponents + vec4<i32>(114)) << vec4<u32>(23u));
  // FP8 products and the incoming half accumulator cannot produce a nonzero
  // result below the smallest half subnormal. Native publishes zero as +0.
  let rounded = nr_round_half4(sums * scale);
  return select(rounded, vec4<f32>(0.0), rounded == vec4<f32>(0.0));
}
fn quad_fdpa_16_16(row: u32, column: u32, accumulator: vec4<f32>) -> vec4<f32> {
  var exponents = select(vec4<i32>(-21),
    max(vec4<i32>((bitcast<vec4<u32>>(abs(accumulator)) >> vec4<u32>(23u)) & vec4<u32>(255u))
      - vec4<i32>(127), vec4<i32>(-14)), accumulator != vec4<f32>(0.0));
  var maximum00: vec4<f16>;
  var maximum01: vec4<f16>;
  var maximum10: vec4<f16>;
  var maximum11: vec4<f16>;
  {
    let k = 4u;
    let a0 = tile_ea[row * 8u + k];
    let b0 = tile_eb[column * 9u + k];
    let b1 = tile_eb[(column + 1u) * 9u + k];
    let b2 = tile_eb[(column + 2u) * 9u + k];
    let b3 = tile_eb[(column + 3u) * 9u + k];
    maximum00 = a0 + b0;
    maximum01 = a0 + b1;
    maximum10 = a0 + b2;
    maximum11 = a0 + b3;
  }
  {
    let k = 5u;
    let a0 = tile_ea[row * 8u + k];
    let b0 = tile_eb[column * 9u + k];
    let b1 = tile_eb[(column + 1u) * 9u + k];
    let b2 = tile_eb[(column + 2u) * 9u + k];
    let b3 = tile_eb[(column + 3u) * 9u + k];
    maximum00 = max(maximum00, a0 + b0);
    maximum01 = max(maximum01, a0 + b1);
    maximum10 = max(maximum10, a0 + b2);
    maximum11 = max(maximum11, a0 + b3);
  }
  {
    let k = 6u;
    let a0 = tile_ea[row * 8u + k];
    let b0 = tile_eb[column * 9u + k];
    let b1 = tile_eb[(column + 1u) * 9u + k];
    let b2 = tile_eb[(column + 2u) * 9u + k];
    let b3 = tile_eb[(column + 3u) * 9u + k];
    maximum00 = max(maximum00, a0 + b0);
    maximum01 = max(maximum01, a0 + b1);
    maximum10 = max(maximum10, a0 + b2);
    maximum11 = max(maximum11, a0 + b3);
  }
  {
    let k = 7u;
    let a0 = tile_ea[row * 8u + k];
    let b0 = tile_eb[column * 9u + k];
    let b1 = tile_eb[(column + 1u) * 9u + k];
    let b2 = tile_eb[(column + 2u) * 9u + k];
    let b3 = tile_eb[(column + 3u) * 9u + k];
    maximum00 = max(maximum00, a0 + b0);
    maximum01 = max(maximum01, a0 + b1);
    maximum10 = max(maximum10, a0 + b2);
    maximum11 = max(maximum11, a0 + b3);
  }
  let maximum = vec4<f16>(maximum_half_exponent(maximum00), maximum_half_exponent(maximum01),
    maximum_half_exponent(maximum10), maximum_half_exponent(maximum11));
  exponents = max(exponents, vec4<i32>(maximum));
  let alignment = bitcast<vec4<f32>>(vec4<u32>(vec4<i32>(140) - exponents) << vec4<u32>(23u));
  var sums = trunc(accumulator * alignment);
  let product_alignment = bitcast<vec4<f32>>(vec4<u32>(vec4<i32>(136) - exponents) << vec4<u32>(23u));
  {
    let k = 4u;
    let a0 = tile_a[row * 8u + k];
    let b0 = tile_b[column * 9u + k];
    let b1 = tile_b[(column + 1u) * 9u + k];
    let b2 = tile_b[(column + 2u) * 9u + k];
    let b3 = tile_b[(column + 3u) * 9u + k];
    sums += trunc(vec4<f32>(vec4<f16>(a0.x)
      * vec4<f16>(b0.x, b1.x, b2.x, b3.x)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.y)
      * vec4<f16>(b0.y, b1.y, b2.y, b3.y)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.z)
      * vec4<f16>(b0.z, b1.z, b2.z, b3.z)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.w)
      * vec4<f16>(b0.w, b1.w, b2.w, b3.w)) * product_alignment);
  }
  {
    let k = 5u;
    let a0 = tile_a[row * 8u + k];
    let b0 = tile_b[column * 9u + k];
    let b1 = tile_b[(column + 1u) * 9u + k];
    let b2 = tile_b[(column + 2u) * 9u + k];
    let b3 = tile_b[(column + 3u) * 9u + k];
    sums += trunc(vec4<f32>(vec4<f16>(a0.x)
      * vec4<f16>(b0.x, b1.x, b2.x, b3.x)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.y)
      * vec4<f16>(b0.y, b1.y, b2.y, b3.y)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.z)
      * vec4<f16>(b0.z, b1.z, b2.z, b3.z)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.w)
      * vec4<f16>(b0.w, b1.w, b2.w, b3.w)) * product_alignment);
  }
  {
    let k = 6u;
    let a0 = tile_a[row * 8u + k];
    let b0 = tile_b[column * 9u + k];
    let b1 = tile_b[(column + 1u) * 9u + k];
    let b2 = tile_b[(column + 2u) * 9u + k];
    let b3 = tile_b[(column + 3u) * 9u + k];
    sums += trunc(vec4<f32>(vec4<f16>(a0.x)
      * vec4<f16>(b0.x, b1.x, b2.x, b3.x)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.y)
      * vec4<f16>(b0.y, b1.y, b2.y, b3.y)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.z)
      * vec4<f16>(b0.z, b1.z, b2.z, b3.z)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.w)
      * vec4<f16>(b0.w, b1.w, b2.w, b3.w)) * product_alignment);
  }
  {
    let k = 7u;
    let a0 = tile_a[row * 8u + k];
    let b0 = tile_b[column * 9u + k];
    let b1 = tile_b[(column + 1u) * 9u + k];
    let b2 = tile_b[(column + 2u) * 9u + k];
    let b3 = tile_b[(column + 3u) * 9u + k];
    sums += trunc(vec4<f32>(vec4<f16>(a0.x)
      * vec4<f16>(b0.x, b1.x, b2.x, b3.x)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.y)
      * vec4<f16>(b0.y, b1.y, b2.y, b3.y)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.z)
      * vec4<f16>(b0.z, b1.z, b2.z, b3.z)) * product_alignment);
    sums += trunc(vec4<f32>(vec4<f16>(a0.w)
      * vec4<f16>(b0.w, b1.w, b2.w, b3.w)) * product_alignment);
  }
  let scale = bitcast<vec4<f32>>(vec4<u32>(exponents + vec4<i32>(114)) << vec4<u32>(23u));
  // FP8 products and the incoming half accumulator cannot produce a nonzero
  // result below the smallest half subnormal. Native publishes zero as +0.
  let rounded = nr_round_half4(sums * scale);
  return select(rounded, vec4<f32>(0.0), rounded == vec4<f32>(0.0));
}

@compute @workgroup_size(8, 16, 1)
fn main(
  @builtin(local_invocation_index) local_index: u32,
  @builtin(workgroup_id) group_id: vec3<u32>,
  @builtin(local_invocation_id) local_id: vec3<u32>,
) {
  let column_groups = (MATMUL_N + 31u) / 32u;
  let batch = group_id.x / column_groups;
  let column_group = group_id.x % column_groups;
  if (params.rows == 0u) { return; }
  let row_group = group_id.y + group_id.z * 65535u;
  let row_base = row_group * 32u + local_id.y * 2u;
  let column_base = column_group * 32u + local_id.x * 4u;
  var sums = array<f32, 8>();
  var tile_sums = array<f32, 8>();
  var partition_sums = array<f32, 8>();

  // Native mma.sync uses FP16 accumulators. Residual/bias values initialize
  // those accumulators before the first K tile; adding them after the matrix
  // product changes every subsequent FP16 rounding step.
  for (var local_row = 0u; local_row < 2u; local_row += 1u) {
    let row = row_base + local_row;
    for (var local_column = 0u; local_column < 4u; local_column += 1u) {
      let column = column_base + local_column;
      if ((MATMUL_ROWS % 32u == 0u || row < MATMUL_ROWS) && (MATMUL_N % 32u == 0u || column < MATMUL_N)) {
        let output_index = row * LAYOUT_OUTPUT_MATRIX_CHANNELS
          + LAYOUT_OUTPUT_COLUMN_OFFSET + batch * MATMUL_N + column;
        var initial = 0.0;
        if ((MATMUL_FLAGS & 1u) != 0u) { initial += load_aux_half(column); }
        if ((MATMUL_FLAGS & 2u) != 0u && (MATMUL_FLAGS & 65536u) == 0u) {
          var residual = load_residual(output_index);
          if ((MATMUL_FLAGS & 8u) != 0u) { residual *= load_aux_half(column); }
          initial += residual;
        }
        sums[local_row * 4u + local_column] = round_accumulator(initial);
      }
    }
  }

  for (var k_base = 0u; k_base < MATMUL_K; k_base += 32u) {
    if ((MATMUL_FLAGS & 256u) != 0u) {
      for (var accumulator = 0u; accumulator < 8u; accumulator += 1u) {
        tile_sums[accumulator] = 0.0;
      }
    }
    for (var tile_index = local_index; tile_index < 256u; tile_index += 128u) {
    let tile_outer = tile_index / 8u;
    let tile_k = (tile_index % 8u) * 4u;
    let input_row = row_group * 32u + tile_outer;
    let output_column = column_group * 32u + tile_outer;
    var weight_word = 0u;
    {
      let k = k_base + tile_k;
      if ((MATMUL_N % 32u == 0u || output_column < MATMUL_N) && (MATMUL_K % 32u == 0u || k < MATMUL_K)) {
        var weight_index: u32;
        if ((MATMUL_FLAGS & 64u) != 0u) {
          weight_index = expert_interleaved_weight_index(k, output_column,
            LAYOUT_WEIGHT_MATRIX_CHANNELS, LAYOUT_WEIGHT_COLUMN_OFFSET);
        } else {
          weight_index = packed_weight_index(k, output_column + LAYOUT_WEIGHT_COLUMN_OFFSET,
            LAYOUT_WEIGHT_MATRIX_CHANNELS);
        }
        let byte_offset = LAYOUT_WEIGHT_BYTE_OFFSET + batch * MATMUL_K * LAYOUT_WEIGHT_MATRIX_CHANNELS + weight_index;
        weight_word = packed_weights[byte_offset / 4u];
        let shift = (byte_offset % 4u) * 8u;
        if (shift != 0u) {
          weight_word = (weight_word >> shift)
            | (packed_weights[byte_offset / 4u + 1u] << (32u - shift));
        }
      }
    }
    var loaded_a = vec4<f16>(0);
    var loaded_b = vec4<f16>(0);
    var ea = vec4<f16>(-100);
    var eb = vec4<f16>(-100);
    let packed_k0 = k_base + tile_k + 0u;
    var packed_input_k0 = select(packed_k0, native_chained_input_index(packed_k0), (MATMUL_FLAGS & 16u) != 0u);
    if ((MATMUL_FLAGS & 128u) != 0u) { packed_input_k0 = native_inverse_chained_input_index(packed_k0); }
    let packed_index0 = input_row * LAYOUT_INPUT_MATRIX_CHANNELS + select(batch * MATMUL_K, 0u, (MATMUL_FLAGS & 131072u) != 0u) + packed_input_k0;
    var packed_word0 = 0u;
    if (input_row < MATMUL_ROWS && packed_k0 < MATMUL_K) {
      packed_word0 = input_values[packed_index0 / 4u];
    }
    let packed_k2 = k_base + tile_k + 2u;
    var packed_input_k2 = select(packed_k2, native_chained_input_index(packed_k2), (MATMUL_FLAGS & 16u) != 0u);
    if ((MATMUL_FLAGS & 128u) != 0u) { packed_input_k2 = native_inverse_chained_input_index(packed_k2); }
    let packed_index2 = input_row * LAYOUT_INPUT_MATRIX_CHANNELS + select(batch * MATMUL_K, 0u, (MATMUL_FLAGS & 131072u) != 0u) + packed_input_k2;
    var packed_word2 = 0u;
    if (input_row < MATMUL_ROWS && packed_k2 < MATMUL_K) {
      packed_word2 = input_values[packed_index2 / 4u];
    }
    for (var part = 0u; part < 4u; part++) {
      let k = k_base + tile_k + part;
      var a = 0.0;
      var b = 0.0;
      let metadata = weight_metadata[(weight_word >> (part * 8u)) & 255u];
      let word = select(packed_word0, packed_word2, part >= 2u);
      let shift = (select(packed_index0, packed_index2, part >= 2u) % 4u + part % 2u) * 8u;
      let a_metadata = weight_metadata[(word >> shift) & 255u];
      if ((MATMUL_K % 32u == 0u || k < MATMUL_K)) {
        b = decode_e4m3((weight_word >> (part * 8u)) & 255u);
      }
      loaded_a[part] = a_metadata.x;
      loaded_b[part] = metadata.x;
      ea[part] = a_metadata.y;
      eb[part] = metadata.y;
    }
    tile_a[tile_index] = loaded_a;
    tile_b[tile_outer * 9u + tile_k / 4u] = loaded_b;
    tile_ea[tile_index] = ea;
    tile_eb[tile_outer * 9u + tile_k / 4u] = eb;
    }
    workgroupBarrier();


    var quad0 = vec4<f32>(sums[0], sums[1], sums[2], sums[3]);
    var quad1 = vec4<f32>(sums[4], sums[5], sums[6], sums[7]);
    if ((MATMUL_FLAGS & 2048u) != 0u) {
      quad0 = quad_fdpa_8_0(local_id.y * 2u, local_id.x * 4u, quad0);
      quad1 = quad_fdpa_8_0(local_id.y * 2u + 1u, local_id.x * 4u, quad1);
      quad0 = quad_fdpa_8_8(local_id.y * 2u, local_id.x * 4u, quad0);
      quad1 = quad_fdpa_8_8(local_id.y * 2u + 1u, local_id.x * 4u, quad1);
      quad0 = quad_fdpa_8_16(local_id.y * 2u, local_id.x * 4u, quad0);
      quad1 = quad_fdpa_8_16(local_id.y * 2u + 1u, local_id.x * 4u, quad1);
      quad0 = quad_fdpa_8_24(local_id.y * 2u, local_id.x * 4u, quad0);
      quad1 = quad_fdpa_8_24(local_id.y * 2u + 1u, local_id.x * 4u, quad1);
    } else if ((MATMUL_FLAGS & 4096u) != 0u) {
      quad0 = quad_fdpa_4_0(local_id.y * 2u, local_id.x * 4u, quad0);
      quad1 = quad_fdpa_4_0(local_id.y * 2u + 1u, local_id.x * 4u, quad1);
      quad0 = quad_fdpa_4_4(local_id.y * 2u, local_id.x * 4u, quad0);
      quad1 = quad_fdpa_4_4(local_id.y * 2u + 1u, local_id.x * 4u, quad1);
      quad0 = quad_fdpa_4_8(local_id.y * 2u, local_id.x * 4u, quad0);
      quad1 = quad_fdpa_4_8(local_id.y * 2u + 1u, local_id.x * 4u, quad1);
      quad0 = quad_fdpa_4_12(local_id.y * 2u, local_id.x * 4u, quad0);
      quad1 = quad_fdpa_4_12(local_id.y * 2u + 1u, local_id.x * 4u, quad1);
      quad0 = quad_fdpa_4_16(local_id.y * 2u, local_id.x * 4u, quad0);
      quad1 = quad_fdpa_4_16(local_id.y * 2u + 1u, local_id.x * 4u, quad1);
      quad0 = quad_fdpa_4_20(local_id.y * 2u, local_id.x * 4u, quad0);
      quad1 = quad_fdpa_4_20(local_id.y * 2u + 1u, local_id.x * 4u, quad1);
      quad0 = quad_fdpa_4_24(local_id.y * 2u, local_id.x * 4u, quad0);
      quad1 = quad_fdpa_4_24(local_id.y * 2u + 1u, local_id.x * 4u, quad1);
      quad0 = quad_fdpa_4_28(local_id.y * 2u, local_id.x * 4u, quad0);
      quad1 = quad_fdpa_4_28(local_id.y * 2u + 1u, local_id.x * 4u, quad1);
    } else {
      quad0 = quad_fdpa_16_0(local_id.y * 2u, local_id.x * 4u, quad0);
      quad1 = quad_fdpa_16_0(local_id.y * 2u + 1u, local_id.x * 4u, quad1);
      quad0 = quad_fdpa_16_16(local_id.y * 2u, local_id.x * 4u, quad0);
      quad1 = quad_fdpa_16_16(local_id.y * 2u + 1u, local_id.x * 4u, quad1);
    }
    sums[0] = quad0.x; sums[1] = quad0.y; sums[2] = quad0.z; sums[3] = quad0.w;
    sums[4] = quad1.x; sums[5] = quad1.y; sums[6] = quad1.z; sums[7] = quad1.w;
    let partition_width = select(
      select(1024u, 512u, (MATMUL_FLAGS & 16384u) != 0u),
      256u,
      (MATMUL_FLAGS & 32768u) != 0u,
    );
    if ((MATMUL_FLAGS & 57344u) != 0u
        && (((k_base + 32u) % partition_width) == 0u
          || (k_base + 32u) >= MATMUL_K)) {
      for (var accumulator = 0u; accumulator < 8u; accumulator += 1u) {
        if (k_base < partition_width) {
          partition_sums[accumulator] = sums[accumulator];
        } else {
          partition_sums[accumulator] = round_accumulator(
            partition_sums[accumulator] + sums[accumulator]);
        }
        sums[accumulator] = 0.0;
      }
    }
    workgroupBarrier();
  }

  if ((MATMUL_FLAGS & 57344u) != 0u) {
    for (var accumulator = 0u; accumulator < 8u; accumulator += 1u) {
      sums[accumulator] = partition_sums[accumulator];
    }
  }

  for (var local_row = 0u; local_row < 2u; local_row += 1u) {
    let row = row_base + local_row;
    var published_pair = 0u;
    for (var local_column = 0u; local_column < 4u; local_column += 1u) {
      let column = column_base + local_column;
      if ((MATMUL_ROWS % 32u == 0u || row < MATMUL_ROWS) && (MATMUL_N % 32u == 0u || column < MATMUL_N)) {
        let output_index = row * LAYOUT_OUTPUT_MATRIX_CHANNELS
          + LAYOUT_OUTPUT_COLUMN_OFFSET + batch * MATMUL_N + column;
        var value = sums[local_row * 4u + local_column];
        if ((MATMUL_FLAGS & 2u) != 0u && (MATMUL_FLAGS & 65536u) != 0u) {
          var residual = load_residual(output_index);
          if ((MATMUL_FLAGS & 8u) != 0u) {
            value = round_accumulator(value + residual * load_aux_half(column));
          } else {
            value = round_accumulator(value + residual);
          }
        }
        if ((MATMUL_FLAGS & 4u) != 0u) {
          let index = pack2x16float(vec2<f32>(vec2<f16>(f16(value), 0.0h))) & 65535u;
          let code = (native_silu_table[index / 4u] >> ((index % 4u) * 8u)) & 255u;
          published_pair |= code << (local_column * 8u);
        } else {
          published_pair |= publish_e4_code(value) << (local_column * 8u);
          raw_values[output_index] = f16(value);
        }
      }
    }
    if (row < MATMUL_ROWS && column_base < MATMUL_N) {
      let column = column_base;
      let output_index = row * LAYOUT_OUTPUT_MATRIX_CHANNELS
          + LAYOUT_OUTPUT_COLUMN_OFFSET + batch * MATMUL_N + column;
      output_values[output_index / 4u] = published_pair;
    }
  }
}
