// GENERATED by tools/gen_wgsl.mjs from the OpenDLSS-NR browser-webgpu port: the window norm half fma, for tools/check_numerics.mjs. Do not edit.
/// Whether an f32 lies exactly halfway between two adjacent halves (subnormal halves included).
fn nr_is_half_tie(value: f32) -> bool {
  let magnitude = bitcast<u32>(value) & 0x7fffffffu;
  if (magnitude >= 0x38800000u) { return (magnitude & 0x1fffu) == 0x1000u; }
  let exponent = magnitude >> 23u;
  if (exponent < 102u) { return false; }
  let mantissa = (magnitude & 0x7fffffu) | 0x800000u;
  let shift = 126u - exponent;
  return (mantissa & ((1u << shift) - 1u)) == (1u << (shift - 1u));
}

/// fma(a, b, c) in half, rounded once (fma.rn.f16). The product of two halves is exact in f32; TwoSum recovers
/// the f32 sum's error exactly. The exact value then lies strictly between the sum and its f32 neighbour towards
/// it, and no half tie can lie strictly between two adjacent f32s: so the sum rounds like the exact value unless
/// the sum is itself a tie, and then the neighbour does. The NVIDIA driver rewrites f32 algebra as if it were
/// exact ((p + c) - c into p, s - (s - c) into c), which would zero the error, so every intermediate passes
/// through an XOR with nr_opaque_zero().
fn nr_norm_fma(a: f16, b: f16, c: f16) -> f16 {
  let opaque_zero = nr_opaque_zero();
  let product = f32(a) * f32(b);
  let addend = f32(c);
  let sum = bitcast<f32>(bitcast<u32>(product + addend) ^ opaque_zero);
  let product_part = bitcast<f32>(bitcast<u32>(sum - addend) ^ opaque_zero);
  let addend_part = bitcast<f32>(bitcast<u32>(sum - product_part) ^ opaque_zero);
  let error = (product - product_part) + (addend - addend_part);
  var bits = bitcast<u32>(sum);
  if (error != 0.0 && nr_is_half_tie(sum)) { bits = select(bits - 1u, bits + 1u, (error > 0.0) == (sum > 0.0)); }
  return f16(round_f16(bitcast<f32>(bits)));
}
