// GENERATED by tools/gen_wgsl.mjs from the OpenDLSS-NR browser-webgpu port: packed E4 SiLU table builder. Do not edit.
enable f16;
fn exact_e4_output_code(value: f32) -> u32 {
  let magnitude = abs(value);
  let bits = bitcast<u32>(magnitude);
  let code = select(u32(magnitude * 512.0), (bits >> 20u) - 960u, magnitude >= 0.015625);
  return code | ((bitcast<u32>(value) >> 24u) & 128u);
}
@group(0) @binding(0) var<storage, read> source: array<vec2<f16>>;
@group(0) @binding(1) var<storage, read_write> result: array<u32>;
@compute @workgroup_size(256)
fn main(@builtin(global_invocation_id) id: vec3<u32>) {
  var word = 0u;
  for (var part = 0u; part < 4u; part++) {
    word |= exact_e4_output_code(f32(source[id.x * 4u + part].y)) << (part * 8u);
  }
  result[id.x] = word;
}
