// GENERATED by tools/gen_wgsl.mjs from the OpenDLSS-NR browser-webgpu port: half SiLU table builder. Do not edit.
enable f16;
fn nr_round_half(value: f32) -> f32 {
  let bits = bitcast<u32>(value);
  let sign = bits & 0x80000000u;
  let magnitude = bits & 0x7fffffffu;
  if (magnitude >= 0x7f800000u) { return value; }
  if (magnitude >= 0x477ff000u) { return bitcast<f32>(sign | 0x7f800000u); }
  if (magnitude >= 0x38800000u) {
    return bitcast<f32>(sign | ((magnitude + 0xfffu + ((magnitude >> 13u) & 1u)) & 0xffffe000u));
  }
  let exponent = magnitude >> 23u;
  if (exponent < 102u) { return bitcast<f32>(sign); }
  let mantissa = (magnitude & 0x7fffffu) | 0x800000u;
  let shift = 126u - exponent;
  var units = mantissa >> shift;
  let remainder = mantissa & ((1u << shift) - 1u);
  let halfway = 1u << (shift - 1u);
  if (remainder > halfway || (remainder == halfway && (units & 1u) != 0u)) { units += 1u; }
  return bitcast<f32>(sign | bitcast<u32>(f32(units) * 5.9604644775390625e-8));
}
fn nr_round_half4(value: vec4<f32>) -> vec4<f32> {
  // The normal half range, [2^-14, 65520), is nearly every value: there it is one vectorized mantissa
  // rounding. Anything else takes the scalar path above.
  let bits = bitcast<vec4<u32>>(value);
  let magnitude = bits & vec4<u32>(0x7fffffffu);
  if (any(magnitude < vec4<u32>(0x38800000u)) || any(magnitude >= vec4<u32>(0x477ff000u))) {
    return vec4<f32>(nr_round_half(value.x), nr_round_half(value.y), nr_round_half(value.z), nr_round_half(value.w));
  }
  let rounded = (magnitude + vec4<u32>(0xfffu) + ((magnitude >> vec4<u32>(13u)) & vec4<u32>(1u)))
    & vec4<u32>(0xffffe000u);
  return bitcast<vec4<f32>>((bits & vec4<u32>(0x80000000u)) | rounded);
}
fn round_accumulator(value: f32) -> f32 { return nr_round_half(value); }
fn mp_cubic_silu(value: f32) -> f32 {
  let bounded = round_accumulator(clamp(value, -4.0, 4.0));
  let absolute = round_accumulator(abs(bounded));
  let inner = round_accumulator(-0.055908203125 * absolute + 0.447265625);
  let polynomial = round_accumulator(bounded * inner + 0.89453125);
  return round_accumulator(value * polynomial);
}
fn fp8_domain(value: f32) -> f32 {
  if (value != value) { return 0.0; }
  let magnitude = min(abs(value), 448.0);
  if (magnitude == 0.0) { return 0.0; }
  var quantized: f32;
  if (magnitude < 0.015625) {
    quantized = round(magnitude * 512.0) / 512.0;
  } else {
    let bits = bitcast<u32>(magnitude);
    quantized = bitcast<f32>((bits + 0x7ffffu + ((bits >> 20u) & 1u)) & 0xfff00000u);
  }
  return select(quantized, -quantized, value < 0.0);
}
@group(0) @binding(0) var<storage, read_write> values: array<vec2<f16>>;
@compute @workgroup_size(256)
fn main(@builtin(global_invocation_id) id: vec3<u32>) {
  let value = f32(vec2<f16>(unpack2x16float(id.x)).x);
  let activated = mp_cubic_silu(value);
  values[id.x] = vec2<f16>(f16(activated), f16(fp8_domain(activated)));
}
