// GENERATED by tools/gen_wgsl.mjs from the OpenDLSS-NR browser-webgpu port: shifted-window attention. Do not edit.
enable f16;
// The publication grid in WGSL. Every function here has a twin in src/numerics.js, which in turn mirrors
// src/numeric.h and src/reference.cpp of the Vulkan implementation; web/selftest.html checks the two against
// each other over exhaustive inputs. See docs/numerics.md in the repository root for why the schedule of
// roundings, and not an error bound, is the contract.
//
// Three browser constraints shape this file:
//
//   * There is no FP8 type. E4M3 lives as bytes inside u32 words and is decoded arithmetically.
//   * There are no cooperative matrices, so the tensor core's k32 step is written out by hand as fixed point.
//   * f16 is an optional feature (shader-f16), and even where it exists it buys nothing here: every rounding
//     has to be placed explicitly, so it is done on the bit pattern and the whole port runs in f32.
//
// Nothing below calls exp2, log2 or fma. WGSL specifies those only to within a few ULP, which is not good
// enough when the result is compared byte for byte; powers of two are built out of the exponent field instead.

/// 2^e, exactly. Callers stay inside the normal range (|e| < 127).
fn pow2(e: i32) -> f32 { return bitcast<f32>(u32(clamp(e, -126, 127) + 127) << 23u); }

/// Shift right with round-to-nearest-even, the rounding every narrowing conversion here uses.
fn round_shift_right_even(value: u32, shift: u32) -> u32 {
  if (shift == 0u) { return value; }
  if (shift > 31u) { return 0u; }
  let quotient = value >> shift;
  let remainder = value & ((1u << shift) - 1u);
  let halfway = 1u << (shift - 1u);
  let up = (remainder > halfway) || (remainder == halfway && (quotient & 1u) != 0u);
  return quotient + select(0u, 1u, up);
}

/// IEEE binary16 bit pattern of an f32, round-to-nearest-even.
fn f16_bits(value: f32) -> u32 {
  let bits = bitcast<u32>(value);
  let sign = (bits >> 16u) & 0x8000u;
  let exponent = (bits >> 23u) & 0xffu;
  let mantissa = bits & 0x7fffffu;
  if (exponent == 0xffu) { return sign | select(0x7c00u, 0x7e00u, mantissa != 0u); }
  var half_exponent = i32(exponent) - 112;
  if (half_exponent >= 31) { return sign | 0x7c00u; }
  if (half_exponent <= 0) {
    if (half_exponent < -10) { return sign; }
    return sign | round_shift_right_even(mantissa | 0x800000u, u32(14 - half_exponent));
  }
  var rounded = round_shift_right_even(mantissa, 13u);
  if (rounded == 0x400u) { rounded = 0u; half_exponent = half_exponent + 1; }
  if (half_exponent >= 31) { return sign | 0x7c00u; }
  return sign | (u32(half_exponent) << 10u) | rounded;
}

/// f32 value of an IEEE binary16 bit pattern, assembled on the bit pattern rather than arithmetically.
///
/// Every half has an exact f32, so this could be written as a multiply and a scale - but not for the infinities
/// and the NaNs, whose payload and sign have to survive, and which an arithmetic form would have to synthesise.
/// Tint also rejects a NaN constant it can fold, so building one from the input is the only way to have one at
/// all. Subnormal halves are normalised by counting leading zeros instead of the reference's shift loop.
fn f16_to_f32(bits: u32) -> f32 {
  let sign = (bits & 0x8000u) << 16u;
  let exponent = (bits >> 10u) & 0x1fu;
  let mantissa = bits & 0x3ffu;
  if (exponent == 0u) {
    if (mantissa == 0u) { return bitcast<f32>(sign); }
    let shift = countLeadingZeros(mantissa) - 21u;   // brings the leading one up to bit 10
    let normalized = (mantissa << shift) & 0x3ffu;   // which the f32 significand then leaves implicit
    return bitcast<f32>(sign | ((113u - shift) << 23u) | (normalized << 13u));
  }
  if (exponent == 0x1fu) { return bitcast<f32>(sign | 0x7f800000u | (mantissa << 13u)); }
  return bitcast<f32>(sign | ((exponent + 112u) << 23u) | (mantissa << 13u));
}

/// One publication to the half grid.
fn round_f16(value: f32) -> f32 { return f16_to_f32(f16_bits(value)); }

/// E4M3FN value of a byte. The one NaN code reads as zero, which is what every consumer in the graph does
/// with it; nothing downstream is given the chance to propagate it.
fn decode_e4m3(bits: u32) -> f32 {
  let negative = (bits & 0x80u) != 0u;
  let exponent = (bits >> 3u) & 0x0fu;
  let mantissa = bits & 0x07u;
  var value: f32;
  if (exponent == 0u) {
    value = f32(mantissa) * pow2(-9);
  } else if (exponent == 15u && mantissa == 7u) {
    value = 0.0;
  } else {
    value = (1.0 + f32(mantissa) * 0.125) * pow2(i32(exponent) - 7);
  }
  return select(value, -value, negative);
}

/// E4M3FN code of an already half-rounded value: RNE, finite saturation at 448, NaN -> +0. The sign of a zero
/// survives, as the hardware conversion leaves it: +0 and -0 decode alike, but the published bytes differ.
fn encode_e4m3(half_bits: u32) -> u32 {
  if ((half_bits & 0x7c00u) == 0x7c00u && (half_bits & 0x03ffu) != 0u) { return 0u; }
  if ((half_bits & 0x7fffu) == 0u) { return (half_bits >> 8u) & 0x80u; }
  let negative = select(0u, 0x80u, (half_bits & 0x8000u) != 0u);
  let exponent = (half_bits >> 10u) & 0x1fu;
  let mantissa = half_bits & 0x3ffu;
  var code: u32;
  if (exponent == 31u) {
    code = 0x7eu;
  } else if (exponent <= 8u) {
    // Below 2^-6 the E4M3 grid is subnormal: the half significand is shifted down onto a fixed step of 2^-9.
    let significand = select(1024u + mantissa, mantissa, exponent == 0u);
    let shift = select(16u - exponent, 15u, exponent == 0u);
    code = min(round_shift_right_even(significand, shift), 8u);
  } else {
    var e4_exponent = exponent - 8u;
    var e4_mantissa = round_shift_right_even(mantissa, 7u);
    if (e4_mantissa == 8u) { e4_mantissa = 0u; e4_exponent = e4_exponent + 1u; }
    let overflow = (e4_exponent > 15u) || (e4_exponent == 15u && e4_mantissa > 6u);
    code = select((e4_exponent << 3u) | e4_mantissa, 0x7eu, overflow);
  }
  return negative | code;
}

/// MpCubicSiLU: five half publications. The two inner steps are f32 fused multiply-adds in native, but
/// both products are exact in f32 - a half times an 8-bit constant, then two halves - so an unfused multiply
/// and add give the same f32 result, and nothing here depends on whether the compiler contracts them.
fn mp_cubic_silu(value: f32) -> f32 {
  let bounded = round_f16(clamp(value, -4.0, 4.0));
  let absolute = round_f16(abs(bounded));
  let inner = round_f16(-0.055908203125 * absolute + 0.447265625);
  let polynomial = round_f16(bounded * inner + 0.89453125);
  return round_f16(value * polynomial);
}

/// The window blocks' attention weight: an affine map on the score, dropped into the half exponent field.
/// The clamp is what keeps the shifted pattern a finite half, so it belongs to the function, not to safety.
/// The affine is an f32 fused multiply-add there, and `score * 0.044921875` is exact, so this matches it.
fn exp_weight(score: f32) -> f32 {
  let affine = clamp(round_f16(score * 0.044921875 + 1.30078125), 1.03125, 1.5693359375);
  return f16_to_f32(((f16_bits(affine) << 5u) + 0x8000u) & 0xffffu);
}

/// The ViT's variant: a 4-bit shift instead of 5, a different bias, and an affine native evaluates in
/// halves rather than f32. The constants below are those half values; the f32 spellings they are usually
/// written as (0.08953946828842163, 1.7093614339828491) are not the numbers the arithmetic sees.
///
/// Evaluating a half fused multiply-add in f32 rounds twice where native rounds once, which normally
/// has to be corrected for. It does not here: the scale is 1467 * 2^-14, so a half score with exponent e puts
/// the product's last bit at 2^(e-24), and landing exactly on a half midpoint of the sum would need that to
/// be an odd multiple of 2^-11 - only possible for e >= 13, where the clamp has long since saturated. Checked
/// over all 63488 finite halves as well.
fn vit_exp_weight(score: f32) -> f32 {
  let affine = clamp(round_f16(score * 0.08953857421875 + 1.708984375), 1.439453125, 1.9775390625);
  return f16_to_f32(((f16_bits(affine) << 4u) + 0x4000u) & 0xffffu);
}

fn normal_exponent(value: f32) -> i32 { return i32((bitcast<u32>(abs(value)) >> 23u) & 0xffu) - 127; }
fn e4m3_exponent(value: f32) -> i32 { return max(normal_exponent(value), -6); }
fn f16_exponent(value: f32) -> i32 { return max(normal_exponent(value), -14); }

// ---------------------------------------------------------------------------------------------------------
// The tensor core's dot product, as fixed point.
//
// A k32 FP8 step aligns 16 products and the incoming accumulator to one shared exponent, truncates each to 13
// fractional bits, sums those exactly, and rounds the total to half once. The helpers below are that schedule
// taken apart, so a GEMM kernel can run it over operands it already holds instead of copying into an array.
//
// Two properties make the aligned sum exact in f32 and i32 alike, which is what lets this be emulated at all:
//
//   * a product of two E4M3 values carries at most 8 significant bits, and scaling by a power of two is exact,
//     so a * b * pow2(13 - max) is formed with no rounding whatsoever before the truncation;
//   * with max >= ea + eb for every term, each truncated term is below 2^15 and 17 of them stay below 2^20.
//
// The second property is why the accumulator can be an i32. The f16 step below needs 24 fractional bits and is
// bounded by 2^30 instead - still inside i32, which matters because WGSL has no 64-bit integer and the Vulkan
// reference accumulates that one in int64.
// ---------------------------------------------------------------------------------------------------------

/// The shared exponent of a step that starts from this accumulator. -21 is the empty value: with no operands
/// and no accumulator the sum is zero and the exponent never reaches the result.
fn f13_start(accumulator: f32) -> i32 { return select(-21, f16_exponent(accumulator), accumulator != 0.0); }

/// Widen the shared exponent to cover one product. A zero operand is skipped rather than clamped: the exponent
/// read off a zero is -127, and lifting it to -6 would drag the whole step's alignment up with it.
fn f13_cover(maximum_exponent: i32, a: f32, b: f32) -> i32 {
  if (a == 0.0 || b == 0.0) { return maximum_exponent; }
  return max(maximum_exponent, e4m3_exponent(a) + e4m3_exponent(b));
}

/// One term of the aligned sum, in units of 2^(max - 13). scale is pow2(13 - max), hoisted by the caller.
fn f13_term(value: f32, scale: f32) -> i32 { return i32(trunc(value * scale)); }

/// The aligned sum, published once to the half grid.
fn f13_finish(units: i32, maximum_exponent: i32) -> f32 {
  return round_f16(f32(units) * pow2(maximum_exponent - 13));
}

/// Exact signed integer times 2^binary_exponent -> half. The f16 step needs this rather than a rounding of the
/// sum, because its fixed-point total carries more significand than a half holds.
fn fixed_to_f16(fixed_sum: i32, binary_exponent: i32) -> f32 {
  if (fixed_sum == 0) { return 0.0; }
  let negative = fixed_sum < 0;
  let magnitude = u32(abs(fixed_sum));
  let msb = 31u - countLeadingZeros(magnitude);
  var value_exponent = i32(msb) + binary_exponent;
  var half_bits = select(0u, 0x8000u, negative);
  if (value_exponent >= -14) {
    var significand: u32;
    if (msb > 10u) { significand = round_shift_right_even(magnitude, msb - 10u); }
    else { significand = magnitude << (10u - msb); }
    if (significand >= 2048u) { significand = 1024u; value_exponent = value_exponent + 1; }
    if (value_exponent >= 16) { half_bits = half_bits | 0x7c00u; }
    else { half_bits = half_bits | (u32(value_exponent + 15) << 10u) | (significand - 1024u); }
  } else {
    let subnormal_scale = binary_exponent + 24;
    var mantissa: u32;
    if (subnormal_scale >= 0) { mantissa = magnitude << u32(subnormal_scale); }
    else { mantissa = round_shift_right_even(magnitude, u32(-subnormal_scale)); }
    if (mantissa == 0u) { return 0.0; }   // the hardware publishes a zero as +0
    half_bits = half_bits | min(mantissa, 1024u);
  }
  return f16_to_f32(half_bits);
}

/// One half of a k32 FP8 step, over 16 products. A GEMM kernel inlines the same four calls over its registers.
fn ada_fp8_fdpa16(a: array<f32, 16>, b: array<f32, 16>, accumulator: f32) -> f32 {
  // A tensor core carries an infinite or NaN C through untouched; aligning it would manufacture a finite value.
  if ((bitcast<u32>(accumulator) & 0x7f800000u) == 0x7f800000u) { return accumulator; }
  var maximum_exponent = f13_start(accumulator);
  for (var i = 0u; i < 16u; i = i + 1u) { maximum_exponent = f13_cover(maximum_exponent, a[i], b[i]); }
  let scale = pow2(13 - maximum_exponent);
  var units = f13_term(accumulator, scale);
  for (var i = 0u; i < 16u; i = i + 1u) { units = units + f13_term(a[i] * b[i], scale); }
  return f13_finish(units, maximum_exponent);
}

/// The f16 step: 8 products against 24 fractional bits. Used by the chains that never narrow to E4M3.
fn ada_f16_fdpa8(a: array<f32, 8>, b: array<f32, 8>, accumulator: f32) -> f32 {
  var maximum_exponent = f13_start(accumulator);
  for (var i = 0u; i < 8u; i = i + 1u) {
    if (a[i] != 0.0 && b[i] != 0.0) {
      maximum_exponent = max(maximum_exponent, f16_exponent(a[i]) + f16_exponent(b[i]));
    }
  }
  let scale = pow2(24 - maximum_exponent);
  var units = i32(trunc(accumulator * scale));
  for (var i = 0u; i < 8u; i = i + 1u) { units = units + i32(trunc(a[i] * b[i] * scale)); }
  return fixed_to_f16(units, maximum_exponent - 24);
}


override WINDOW_WIDTH:u32=0u;
override WINDOW_HEIGHT:u32=0u;
override WINDOW_CHANNELS:u32=0u;
override WINDOW_SHIFT_X:u32=0u;
override WINDOW_SHIFT_Y:u32=0u;
override WINDOW_USE_RELATIVE_BIAS:u32=0u;
override WINDOW_VALUE_GROUP_ORDER:u32=0u;
struct WindowParams {
  tokens: u32, heads: u32, width: u32, height: u32,
  channels: u32, shift_x: u32, shift_y: u32, use_relative_bias: u32,
}

@group(0) @binding(0) var<uniform> attention_params: WindowParams;
@group(0) @binding(1) var<storage, read> attention_qkv: array<f16>;      // raw half QKV [tokens][channels*3]
@group(0) @binding(2) var<storage, read> attention_scales: array<f32>;   // the learned per-head scale
@group(0) @binding(3) var<storage, read> attention_prior: array<f16>;    // [heads][64 query][64 key]
@group(0) @binding(6) var<storage, read_write> attention_output: array<u32>;   // E4M3 [tokens][channels]

fn round_attention_half(value: f32) -> f32 { return round_f16(value); }

/** The E4M3 publication as a value, for the operands that stay in registers. */
fn publish_fp8(value: f32) -> f32 { return decode_e4m3(encode_e4m3(f16_bits(value))); }

/** The same publication as the byte the output tensor stores. */
fn publish_e4_code(value: f32) -> u32 { return encode_e4m3(f16_bits(value)); }

fn native_exp_weight(score: f16) -> f16 { return f16(exp_weight(f32(score))); }

// Both operands are halves, so their product is exact in f32 and the single rounding here is the fused
// multiply-add's own. This is the pair fold the normalization's square sum is specified with.
/// The window kernel's opaque zero: token counts are below 2^31.
fn nr_opaque_zero() -> u32 { return attention_params.tokens >> 31u; }
/// Whether an f32 lies exactly halfway between two adjacent halves (subnormal halves included).
fn nr_is_half_tie(value: f32) -> bool {
  let magnitude = bitcast<u32>(value) & 0x7fffffffu;
  if (magnitude >= 0x38800000u) { return (magnitude & 0x1fffu) == 0x1000u; }
  let exponent = magnitude >> 23u;
  if (exponent < 102u) { return false; }
  let mantissa = (magnitude & 0x7fffffu) | 0x800000u;
  let shift = 126u - exponent;
  return (mantissa & ((1u << shift) - 1u)) == (1u << (shift - 1u));
}

/// fma(a, b, c) in half, rounded once (fma.rn.f16). The product of two halves is exact in f32; TwoSum recovers
/// the f32 sum's error exactly. The exact value then lies strictly between the sum and its f32 neighbour towards
/// it, and no half tie can lie strictly between two adjacent f32s: so the sum rounds like the exact value unless
/// the sum is itself a tie, and then the neighbour does. The NVIDIA driver rewrites f32 algebra as if it were
/// exact ((p + c) - c into p, s - (s - c) into c), which would zero the error, so every intermediate passes
/// through an XOR with nr_opaque_zero().
fn nr_norm_fma(a: f16, b: f16, c: f16) -> f16 {
  let opaque_zero = nr_opaque_zero();
  let product = f32(a) * f32(b);
  let addend = f32(c);
  let sum = bitcast<f32>(bitcast<u32>(product + addend) ^ opaque_zero);
  let product_part = bitcast<f32>(bitcast<u32>(sum - addend) ^ opaque_zero);
  let addend_part = bitcast<f32>(bitcast<u32>(sum - product_part) ^ opaque_zero);
  let error = (product - product_part) + (addend - addend_part);
  var bits = bitcast<u32>(sum);
  if (error != 0.0 && nr_is_half_tie(sum)) { bits = select(bits - 1u, bits + 1u, (error > 0.0) == (sum > 0.0)); }
  return f16(round_f16(bitcast<f32>(bits)));
}

/** Physical (4x4-tiled) token -> natural row-major token inside an 8x8 window. */
fn inverse_tiled_token(token: u32) -> u32 {
  let tile = token >> 4u;
  let within = token & 15u;
  let x = (tile & 1u) * 4u + (within & 3u);
  let y = (tile >> 1u) * 4u + (within >> 2u);
  return y * 8u + x;
}

// The learned prior is the C accumulator of the score matrix multiply, so the model stores it as 16x16
// accumulator tiles rather than as a matrix. src/model.js untangles that once, into natural query and key.
fn load_relative_bias(head: u32, query: u32, key: u32) -> f32 {
  return f32(attention_prior[(head * 64u + query) * 64u + key]);
}
var<workgroup> window_norms: array<vec2<f16>, 64>;
var<workgroup> vector_q: array<vec4<f16>, 256>;
var<workgroup> vector_k: array<vec4<f16>, 576>;
var<workgroup> vector_v: array<vec4<f16>, 544>;
var<workgroup> vector_scores: array<vec4<f16>, 512>;
var<workgroup> packed_k: array<u32, 512>;
var<workgroup> packed_scores: array<u32, 512>;
fn packed_window_exponents(v: vec4<f32>) -> u32 {
  let exponents = vec4<i32>(e4m3_exponent(v.x), e4m3_exponent(v.y),
    e4m3_exponent(v.z), e4m3_exponent(v.w));
  let bytes = select(vec4<u32>(0), vec4<u32>(exponents + vec4<i32>(106)), v != vec4<f32>(0));
  return bytes.x | (bytes.y << 8u) | (bytes.z << 16u) | (bytes.w << 24u);
}
fn maximum_window_exponent(current: u32, packed: u32) -> u32 {
  let rotated8 = (packed << 8u) | (packed >> 24u);
  let rotated16 = (packed << 16u) | (packed >> 16u);
  let rotated24 = (packed << 24u) | (packed >> 8u);
  return max(current, max(max(packed, rotated8), max(rotated16, rotated24)) >> 24u);
}

var<workgroup> tiled_reciprocals: array<f16, 32>;

fn tiled_qk_0(query: u32, key: u32, accumulator: f32) -> f32 {
  var maximum = 191u;
  if (accumulator != 0.0) { maximum = u32(f16_exponent(accumulator) + 212); }
  {
    let c = 0u;
    maximum = maximum_window_exponent(maximum, packed_scores[query * 8u + c] + packed_k[c * 64u + key]);
  }
  {
    let c = 1u;
    maximum = maximum_window_exponent(maximum, packed_scores[query * 8u + c] + packed_k[c * 64u + key]);
  }
  {
    let c = 2u;
    maximum = maximum_window_exponent(maximum, packed_scores[query * 8u + c] + packed_k[c * 64u + key]);
  }
  {
    let c = 3u;
    maximum = maximum_window_exponent(maximum, packed_scores[query * 8u + c] + packed_k[c * 64u + key]);
  }
  let exponent = i32(maximum) - 212;
  let alignment = bitcast<f32>(u32(140 - exponent) << 23u);
  var sum = trunc(accumulator * alignment);
  {
    let c = 0u;
    let a = vec4<f32>(vector_q[query * 8u + c]);
    let b = vec4<f32>(vector_k[key * 9u + c]);
    sum += trunc((a.x * b.x) * alignment);
    sum += trunc((a.y * b.y) * alignment);
    sum += trunc((a.z * b.z) * alignment);
    sum += trunc((a.w * b.w) * alignment);
  }
  {
    let c = 1u;
    let a = vec4<f32>(vector_q[query * 8u + c]);
    let b = vec4<f32>(vector_k[key * 9u + c]);
    sum += trunc((a.x * b.x) * alignment);
    sum += trunc((a.y * b.y) * alignment);
    sum += trunc((a.z * b.z) * alignment);
    sum += trunc((a.w * b.w) * alignment);
  }
  {
    let c = 2u;
    let a = vec4<f32>(vector_q[query * 8u + c]);
    let b = vec4<f32>(vector_k[key * 9u + c]);
    sum += trunc((a.x * b.x) * alignment);
    sum += trunc((a.y * b.y) * alignment);
    sum += trunc((a.z * b.z) * alignment);
    sum += trunc((a.w * b.w) * alignment);
  }
  {
    let c = 3u;
    let a = vec4<f32>(vector_q[query * 8u + c]);
    let b = vec4<f32>(vector_k[key * 9u + c]);
    sum += trunc((a.x * b.x) * alignment);
    sum += trunc((a.y * b.y) * alignment);
    sum += trunc((a.z * b.z) * alignment);
    sum += trunc((a.w * b.w) * alignment);
  }
  return round_attention_half(select(sum, 0.0, sum == 0.0) * bitcast<f32>(u32(exponent + 114) << 23u));
}
fn tiled_qk_16(query: u32, key: u32, accumulator: f32) -> f32 {
  var maximum = 191u;
  if (accumulator != 0.0) { maximum = u32(f16_exponent(accumulator) + 212); }
  {
    let c = 4u;
    maximum = maximum_window_exponent(maximum, packed_scores[query * 8u + c] + packed_k[c * 64u + key]);
  }
  {
    let c = 5u;
    maximum = maximum_window_exponent(maximum, packed_scores[query * 8u + c] + packed_k[c * 64u + key]);
  }
  {
    let c = 6u;
    maximum = maximum_window_exponent(maximum, packed_scores[query * 8u + c] + packed_k[c * 64u + key]);
  }
  {
    let c = 7u;
    maximum = maximum_window_exponent(maximum, packed_scores[query * 8u + c] + packed_k[c * 64u + key]);
  }
  let exponent = i32(maximum) - 212;
  let alignment = bitcast<f32>(u32(140 - exponent) << 23u);
  var sum = trunc(accumulator * alignment);
  {
    let c = 4u;
    let a = vec4<f32>(vector_q[query * 8u + c]);
    let b = vec4<f32>(vector_k[key * 9u + c]);
    sum += trunc((a.x * b.x) * alignment);
    sum += trunc((a.y * b.y) * alignment);
    sum += trunc((a.z * b.z) * alignment);
    sum += trunc((a.w * b.w) * alignment);
  }
  {
    let c = 5u;
    let a = vec4<f32>(vector_q[query * 8u + c]);
    let b = vec4<f32>(vector_k[key * 9u + c]);
    sum += trunc((a.x * b.x) * alignment);
    sum += trunc((a.y * b.y) * alignment);
    sum += trunc((a.z * b.z) * alignment);
    sum += trunc((a.w * b.w) * alignment);
  }
  {
    let c = 6u;
    let a = vec4<f32>(vector_q[query * 8u + c]);
    let b = vec4<f32>(vector_k[key * 9u + c]);
    sum += trunc((a.x * b.x) * alignment);
    sum += trunc((a.y * b.y) * alignment);
    sum += trunc((a.z * b.z) * alignment);
    sum += trunc((a.w * b.w) * alignment);
  }
  {
    let c = 7u;
    let a = vec4<f32>(vector_q[query * 8u + c]);
    let b = vec4<f32>(vector_k[key * 9u + c]);
    sum += trunc((a.x * b.x) * alignment);
    sum += trunc((a.y * b.y) * alignment);
    sum += trunc((a.z * b.z) * alignment);
    sum += trunc((a.w * b.w) * alignment);
  }
  return round_attention_half(select(sum, 0.0, sum == 0.0) * bitcast<f32>(u32(exponent + 114) << 23u));
}
fn tiled_qk(query:u32, key:u32, start:u32, accumulator:f32)->f32 {
  if(start==0u){return tiled_qk_0(query,key,accumulator);}
  return tiled_qk_16(query,key,accumulator);
}

fn tiled_score(query: u32, index: u32) -> f16 {
  return vector_scores[query * 16u + index / 4u][index % 4u];
}

fn tiled_softmax_pair(query: u32, pair: u32, parity: u32) -> f16 {
  let key = pair * 2u + parity;
  let blocks01 = tiled_score(query, key) + tiled_score(query, key + 8u);
  let blocks23 = tiled_score(query, key + 16u) + tiled_score(query, key + 24u);
  let blocks45 = tiled_score(query, key + 32u) + tiled_score(query, key + 40u);
  let blocks67 = tiled_score(query, key + 48u) + tiled_score(query, key + 56u);
  return ((blocks01 + blocks23) + blocks45) + blocks67;
}

fn tiled_softmax_sum(query: u32) -> f16 {
  let even = ((tiled_softmax_pair(query, 0u, 0u) + tiled_softmax_pair(query, 1u, 0u))
    + tiled_softmax_pair(query, 2u, 0u)) + tiled_softmax_pair(query, 3u, 0u);
  let odd = ((tiled_softmax_pair(query, 0u, 1u) + tiled_softmax_pair(query, 1u, 1u))
    + tiled_softmax_pair(query, 2u, 1u)) + tiled_softmax_pair(query, 3u, 1u);
  return even + odd;
}

fn tiled_value_0(query: u32, component: u32, accumulator: f32) -> f32 {
  var maximum = 191u;
  if (accumulator != 0.0) { maximum = u32(f16_exponent(accumulator) + 212); }
  {
    let c = 0u;
    maximum = maximum_window_exponent(maximum, packed_scores[query * 16u + c] + packed_k[c * 32u + component]);
  }
  {
    let c = 1u;
    maximum = maximum_window_exponent(maximum, packed_scores[query * 16u + c] + packed_k[c * 32u + component]);
  }
  {
    let c = 2u;
    maximum = maximum_window_exponent(maximum, packed_scores[query * 16u + c] + packed_k[c * 32u + component]);
  }
  {
    let c = 3u;
    maximum = maximum_window_exponent(maximum, packed_scores[query * 16u + c] + packed_k[c * 32u + component]);
  }
  let exponent = i32(maximum) - 212;
  let alignment = bitcast<f32>(u32(140 - exponent) << 23u);
  var sum = trunc(accumulator * alignment);
  let product_alignment = bitcast<f32>(u32(136 - exponent) << 23u);
  {
    let c = 0u;
    let product = vec4<f32>(vector_scores[query * 16u + c]
      * vector_v[component * 17u + c]);
    sum += trunc(product.x * product_alignment);
    sum += trunc(product.y * product_alignment);
    sum += trunc(product.z * product_alignment);
    sum += trunc(product.w * product_alignment);
  }
  {
    let c = 1u;
    let product = vec4<f32>(vector_scores[query * 16u + c]
      * vector_v[component * 17u + c]);
    sum += trunc(product.x * product_alignment);
    sum += trunc(product.y * product_alignment);
    sum += trunc(product.z * product_alignment);
    sum += trunc(product.w * product_alignment);
  }
  {
    let c = 2u;
    let product = vec4<f32>(vector_scores[query * 16u + c]
      * vector_v[component * 17u + c]);
    sum += trunc(product.x * product_alignment);
    sum += trunc(product.y * product_alignment);
    sum += trunc(product.z * product_alignment);
    sum += trunc(product.w * product_alignment);
  }
  {
    let c = 3u;
    let product = vec4<f32>(vector_scores[query * 16u + c]
      * vector_v[component * 17u + c]);
    sum += trunc(product.x * product_alignment);
    sum += trunc(product.y * product_alignment);
    sum += trunc(product.z * product_alignment);
    sum += trunc(product.w * product_alignment);
  }
  return round_attention_half(select(sum, 0.0, sum == 0.0) * bitcast<f32>(u32(exponent + 114) << 23u));
}
fn tiled_value_16(query: u32, component: u32, accumulator: f32) -> f32 {
  var maximum = 191u;
  if (accumulator != 0.0) { maximum = u32(f16_exponent(accumulator) + 212); }
  {
    let c = 4u;
    maximum = maximum_window_exponent(maximum, packed_scores[query * 16u + c] + packed_k[c * 32u + component]);
  }
  {
    let c = 5u;
    maximum = maximum_window_exponent(maximum, packed_scores[query * 16u + c] + packed_k[c * 32u + component]);
  }
  {
    let c = 6u;
    maximum = maximum_window_exponent(maximum, packed_scores[query * 16u + c] + packed_k[c * 32u + component]);
  }
  {
    let c = 7u;
    maximum = maximum_window_exponent(maximum, packed_scores[query * 16u + c] + packed_k[c * 32u + component]);
  }
  let exponent = i32(maximum) - 212;
  let alignment = bitcast<f32>(u32(140 - exponent) << 23u);
  var sum = trunc(accumulator * alignment);
  let product_alignment = bitcast<f32>(u32(136 - exponent) << 23u);
  {
    let c = 4u;
    let product = vec4<f32>(vector_scores[query * 16u + c]
      * vector_v[component * 17u + c]);
    sum += trunc(product.x * product_alignment);
    sum += trunc(product.y * product_alignment);
    sum += trunc(product.z * product_alignment);
    sum += trunc(product.w * product_alignment);
  }
  {
    let c = 5u;
    let product = vec4<f32>(vector_scores[query * 16u + c]
      * vector_v[component * 17u + c]);
    sum += trunc(product.x * product_alignment);
    sum += trunc(product.y * product_alignment);
    sum += trunc(product.z * product_alignment);
    sum += trunc(product.w * product_alignment);
  }
  {
    let c = 6u;
    let product = vec4<f32>(vector_scores[query * 16u + c]
      * vector_v[component * 17u + c]);
    sum += trunc(product.x * product_alignment);
    sum += trunc(product.y * product_alignment);
    sum += trunc(product.z * product_alignment);
    sum += trunc(product.w * product_alignment);
  }
  {
    let c = 7u;
    let product = vec4<f32>(vector_scores[query * 16u + c]
      * vector_v[component * 17u + c]);
    sum += trunc(product.x * product_alignment);
    sum += trunc(product.y * product_alignment);
    sum += trunc(product.z * product_alignment);
    sum += trunc(product.w * product_alignment);
  }
  return round_attention_half(select(sum, 0.0, sum == 0.0) * bitcast<f32>(u32(exponent + 114) << 23u));
}
fn tiled_value_32(query: u32, component: u32, accumulator: f32) -> f32 {
  var maximum = 191u;
  if (accumulator != 0.0) { maximum = u32(f16_exponent(accumulator) + 212); }
  {
    let c = 8u;
    maximum = maximum_window_exponent(maximum, packed_scores[query * 16u + c] + packed_k[c * 32u + component]);
  }
  {
    let c = 9u;
    maximum = maximum_window_exponent(maximum, packed_scores[query * 16u + c] + packed_k[c * 32u + component]);
  }
  {
    let c = 10u;
    maximum = maximum_window_exponent(maximum, packed_scores[query * 16u + c] + packed_k[c * 32u + component]);
  }
  {
    let c = 11u;
    maximum = maximum_window_exponent(maximum, packed_scores[query * 16u + c] + packed_k[c * 32u + component]);
  }
  let exponent = i32(maximum) - 212;
  let alignment = bitcast<f32>(u32(140 - exponent) << 23u);
  var sum = trunc(accumulator * alignment);
  let product_alignment = bitcast<f32>(u32(136 - exponent) << 23u);
  {
    let c = 8u;
    let product = vec4<f32>(vector_scores[query * 16u + c]
      * vector_v[component * 17u + c]);
    sum += trunc(product.x * product_alignment);
    sum += trunc(product.y * product_alignment);
    sum += trunc(product.z * product_alignment);
    sum += trunc(product.w * product_alignment);
  }
  {
    let c = 9u;
    let product = vec4<f32>(vector_scores[query * 16u + c]
      * vector_v[component * 17u + c]);
    sum += trunc(product.x * product_alignment);
    sum += trunc(product.y * product_alignment);
    sum += trunc(product.z * product_alignment);
    sum += trunc(product.w * product_alignment);
  }
  {
    let c = 10u;
    let product = vec4<f32>(vector_scores[query * 16u + c]
      * vector_v[component * 17u + c]);
    sum += trunc(product.x * product_alignment);
    sum += trunc(product.y * product_alignment);
    sum += trunc(product.z * product_alignment);
    sum += trunc(product.w * product_alignment);
  }
  {
    let c = 11u;
    let product = vec4<f32>(vector_scores[query * 16u + c]
      * vector_v[component * 17u + c]);
    sum += trunc(product.x * product_alignment);
    sum += trunc(product.y * product_alignment);
    sum += trunc(product.z * product_alignment);
    sum += trunc(product.w * product_alignment);
  }
  return round_attention_half(select(sum, 0.0, sum == 0.0) * bitcast<f32>(u32(exponent + 114) << 23u));
}
fn tiled_value_48(query: u32, component: u32, accumulator: f32) -> f32 {
  var maximum = 191u;
  if (accumulator != 0.0) { maximum = u32(f16_exponent(accumulator) + 212); }
  {
    let c = 12u;
    maximum = maximum_window_exponent(maximum, packed_scores[query * 16u + c] + packed_k[c * 32u + component]);
  }
  {
    let c = 13u;
    maximum = maximum_window_exponent(maximum, packed_scores[query * 16u + c] + packed_k[c * 32u + component]);
  }
  {
    let c = 14u;
    maximum = maximum_window_exponent(maximum, packed_scores[query * 16u + c] + packed_k[c * 32u + component]);
  }
  {
    let c = 15u;
    maximum = maximum_window_exponent(maximum, packed_scores[query * 16u + c] + packed_k[c * 32u + component]);
  }
  let exponent = i32(maximum) - 212;
  let alignment = bitcast<f32>(u32(140 - exponent) << 23u);
  var sum = trunc(accumulator * alignment);
  let product_alignment = bitcast<f32>(u32(136 - exponent) << 23u);
  {
    let c = 12u;
    let product = vec4<f32>(vector_scores[query * 16u + c]
      * vector_v[component * 17u + c]);
    sum += trunc(product.x * product_alignment);
    sum += trunc(product.y * product_alignment);
    sum += trunc(product.z * product_alignment);
    sum += trunc(product.w * product_alignment);
  }
  {
    let c = 13u;
    let product = vec4<f32>(vector_scores[query * 16u + c]
      * vector_v[component * 17u + c]);
    sum += trunc(product.x * product_alignment);
    sum += trunc(product.y * product_alignment);
    sum += trunc(product.z * product_alignment);
    sum += trunc(product.w * product_alignment);
  }
  {
    let c = 14u;
    let product = vec4<f32>(vector_scores[query * 16u + c]
      * vector_v[component * 17u + c]);
    sum += trunc(product.x * product_alignment);
    sum += trunc(product.y * product_alignment);
    sum += trunc(product.z * product_alignment);
    sum += trunc(product.w * product_alignment);
  }
  {
    let c = 15u;
    let product = vec4<f32>(vector_scores[query * 16u + c]
      * vector_v[component * 17u + c]);
    sum += trunc(product.x * product_alignment);
    sum += trunc(product.y * product_alignment);
    sum += trunc(product.z * product_alignment);
    sum += trunc(product.w * product_alignment);
  }
  return round_attention_half(select(sum, 0.0, sum == 0.0) * bitcast<f32>(u32(exponent + 114) << 23u));
}
fn tiled_value(query:u32, component:u32, start:u32, accumulator:f32)->f32 {
  if(start==0u){return tiled_value_0(query,component,accumulator);}
  if(start==16u){return tiled_value_16(query,component,accumulator);}
  if(start==32u){return tiled_value_32(query,component,accumulator);}
  return tiled_value_48(query,component,accumulator);
}

@compute @workgroup_size(512)
fn attend_window_tiled(@builtin(local_invocation_index) lane: u32,
  @builtin(workgroup_id) gid: vec3<u32>) {
  let windows_x = (WINDOW_WIDTH + WINDOW_SHIFT_X + 7u) / 8u;
  let windows_y = (WINDOW_HEIGHT + WINDOW_SHIFT_Y + 7u) / 8u;
  let task = gid.y + gid.z * 65535u;
  if (task >= windows_x * windows_y * 2u) { return; }
  let window = task / 2u;
  let query_origin = (task % 2u) * 32u;
  let wx = i32((window % windows_x) * 8u) - i32(WINDOW_SHIFT_X);
  let wy = i32((window / windows_x) * 8u) - i32(WINDOW_SHIFT_Y);
  let head = gid.x;
  for (var first = 0u; first < 64u; first += 64u) {
    let token = first + lane / 8u; let component = lane % 8u;
    let nx = wx + i32(token % 8u); let ny = wy + i32(token / 8u);
    var q0 = 0.0h; var q8 = 0.0h; var q16 = 0.0h; var q24 = 0.0h;
    var k0 = 0.0h; var k8 = 0.0h; var k16 = 0.0h; var k24 = 0.0h;
    if (nx >= 0 && ny >= 0 && nx < i32(WINDOW_WIDTH) && ny < i32(WINDOW_HEIGHT)) {
      let base = (u32(ny) * WINDOW_WIDTH + u32(nx)) * WINDOW_CHANNELS * 3u
        + head * 96u + component;

      q0 = f16(attention_qkv[base + 0u]);
      k0 = f16(attention_qkv[base + 32u]);
      q8 = f16(attention_qkv[base + 8u]);
      k8 = f16(attention_qkv[base + 40u]);
      q16 = f16(attention_qkv[base + 16u]);
      k16 = f16(attention_qkv[base + 48u]);
      q24 = f16(attention_qkv[base + 24u]);
      k24 = f16(attention_qkv[base + 56u]);
    }
    let q_low = nr_norm_fma(q0, q0, q16 * q16);
    let q_high = nr_norm_fma(q8, q8, q24 * q24);
    let k_low = nr_norm_fma(k0, k0, k16 * k16);
    let k_high = nr_norm_fma(k8, k8, k24 * k24);
    vector_k[lane] = vec4<f16>(q_low + q_high, k_low + k_high, 0.0h, 0.0h);
    workgroupBarrier();
    for (var stride = 4u; stride > 0u; stride >>= 1u) {
      if (component < stride) { vector_k[lane] += vector_k[lane + stride]; }
      workgroupBarrier();
    }
    if (component == 0u) {
      let squares = vector_k[lane];
      // 1/sqrt rather than inverseSqrt: WGSL gives the latter an accuracy allowance, and while the half
      // rounding would absorb it almost everywhere, "almost" is not what this port is checked against.
      window_norms[token] = vec2<f16>(f16(1.0 / sqrt(f32(squares.x))), f16(1.0 / sqrt(f32(squares.y))));
    }
    workgroupBarrier();
  }
  let scale = attention_scales[head];

  for (var linear = lane; linear < 512u; linear += 512u) {
    let key = linear % 64u; let c = linear / 64u;
    let x = wx + i32(key % 8u); let y = wy + i32(key / 8u);
    var k = vec4<f16>(0);
    if (x >= 0 && y >= 0 && x < i32(WINDOW_WIDTH) && y < i32(WINDOW_HEIGHT)) {
      let base = (u32(y) * WINDOW_WIDTH + u32(x)) * WINDOW_CHANNELS * 3u
        + head * 96u + 32u + c * 4u;
      k.x = f16(publish_fp8(f32(f16(attention_qkv[base + 0u]) * window_norms[key].y)));
      k.y = f16(publish_fp8(f32(f16(attention_qkv[base + 1u]) * window_norms[key].y)));
      k.z = f16(publish_fp8(f32(f16(attention_qkv[base + 2u]) * window_norms[key].y)));
      k.w = f16(publish_fp8(f32(f16(attention_qkv[base + 3u]) * window_norms[key].y)));
    }
    vector_k[key * 9u + c] = k;
    packed_k[linear] = packed_window_exponents(vec4<f32>(k));
    let component = linear % 32u; let first = (linear / 32u) * 4u;
    var v = vec4<f16>(0);

    {
      let token = inverse_tiled_token(first + 0u);
      let vx = wx + i32(token % 8u); let vy = wy + i32(token / 8u);
      if (vx >= 0 && vy >= 0 && vx < i32(WINDOW_WIDTH) && vy < i32(WINDOW_HEIGHT)) {
        v.x = f16(publish_fp8(f32(attention_qkv[(u32(vy) * WINDOW_WIDTH + u32(vx)) * WINDOW_CHANNELS * 3u
          + head * 96u + 64u + component])));
      }
    }
    {
      let token = inverse_tiled_token(first + 1u);
      let vx = wx + i32(token % 8u); let vy = wy + i32(token / 8u);
      if (vx >= 0 && vy >= 0 && vx < i32(WINDOW_WIDTH) && vy < i32(WINDOW_HEIGHT)) {
        v.y = f16(publish_fp8(f32(attention_qkv[(u32(vy) * WINDOW_WIDTH + u32(vx)) * WINDOW_CHANNELS * 3u
          + head * 96u + 64u + component])));
      }
    }
    {
      let token = inverse_tiled_token(first + 2u);
      let vx = wx + i32(token % 8u); let vy = wy + i32(token / 8u);
      if (vx >= 0 && vy >= 0 && vx < i32(WINDOW_WIDTH) && vy < i32(WINDOW_HEIGHT)) {
        v.z = f16(publish_fp8(f32(attention_qkv[(u32(vy) * WINDOW_WIDTH + u32(vx)) * WINDOW_CHANNELS * 3u
          + head * 96u + 64u + component])));
      }
    }
    {
      let token = inverse_tiled_token(first + 3u);
      let vx = wx + i32(token % 8u); let vy = wy + i32(token / 8u);
      if (vx >= 0 && vy >= 0 && vx < i32(WINDOW_WIDTH) && vy < i32(WINDOW_HEIGHT)) {
        v.w = f16(publish_fp8(f32(attention_qkv[(u32(vy) * WINDOW_WIDTH + u32(vx)) * WINDOW_CHANNELS * 3u
          + head * 96u + 64u + component])));
      }
    }
    vector_v[component * 17u + first / 4u] = v;
  }
  for (var linear = lane; linear < 256u; linear += 512u) {
    let query = query_origin + linear / 8u;
    let x = wx + i32(query % 8u); let y = wy + i32(query / 8u);
    var q = vec4<f16>(0);
    if (x >= 0 && y >= 0 && x < i32(WINDOW_WIDTH) && y < i32(WINDOW_HEIGHT)) {
      let base = (u32(y) * WINDOW_WIDTH + u32(x)) * WINDOW_CHANNELS * 3u
        + head * 96u + (linear % 8u) * 4u;
      q.x = f16(publish_fp8(f32(f16(f16(attention_qkv[base + 0u]) * window_norms[query].x) * f16(scale))));
      q.y = f16(publish_fp8(f32(f16(f16(attention_qkv[base + 1u]) * window_norms[query].x) * f16(scale))));
      q.z = f16(publish_fp8(f32(f16(f16(attention_qkv[base + 2u]) * window_norms[query].x) * f16(scale))));
      q.w = f16(publish_fp8(f32(f16(f16(attention_qkv[base + 3u]) * window_norms[query].x) * f16(scale))));
    }
    vector_q[linear] = q;
    packed_scores[linear] = packed_window_exponents(vec4<f32>(q));
  }
  workgroupBarrier();
  for (var linear = lane; linear < 512u; linear += 512u) {
    let query = linear / 16u; let first = (linear % 16u) * 4u;
    var score = vec4<f16>(0);
    {
      let key = inverse_tiled_token(first + 0u);
      var prior = 0.0;
      if (WINDOW_USE_RELATIVE_BIAS != 0u) { prior = load_relative_bias(head, query_origin + query, key); }
      let low = tiled_qk(query, key, 0u, prior);
      score.x = native_exp_weight(f16(tiled_qk(query, key, 16u, low)));
    }
    {
      let key = inverse_tiled_token(first + 1u);
      var prior = 0.0;
      if (WINDOW_USE_RELATIVE_BIAS != 0u) { prior = load_relative_bias(head, query_origin + query, key); }
      let low = tiled_qk(query, key, 0u, prior);
      score.y = native_exp_weight(f16(tiled_qk(query, key, 16u, low)));
    }
    {
      let key = inverse_tiled_token(first + 2u);
      var prior = 0.0;
      if (WINDOW_USE_RELATIVE_BIAS != 0u) { prior = load_relative_bias(head, query_origin + query, key); }
      let low = tiled_qk(query, key, 0u, prior);
      score.z = native_exp_weight(f16(tiled_qk(query, key, 16u, low)));
    }
    {
      let key = inverse_tiled_token(first + 3u);
      var prior = 0.0;
      if (WINDOW_USE_RELATIVE_BIAS != 0u) { prior = load_relative_bias(head, query_origin + query, key); }
      let low = tiled_qk(query, key, 0u, prior);
      score.w = native_exp_weight(f16(tiled_qk(query, key, 16u, low)));
    }
    vector_scores[linear] = score;
  }
  workgroupBarrier();
  if (lane < 32u) { tiled_reciprocals[lane] = f16(1.0 / f32(tiled_softmax_sum(lane))); }
  workgroupBarrier();
  for (var linear = lane; linear < 512u; linear += 512u) {
    let component = linear % 32u; let c = linear / 32u;
    let v = vector_v[component * 17u + c];
    packed_k[linear] = packed_window_exponents(vec4<f32>(v));
    vector_v[component * 17u + c] = v * vec4<f16>(4);
  }
  for (var linear = lane; linear < 512u; linear += 512u) {
    let weight = vector_scores[linear] * vec4<f16>(tiled_reciprocals[linear / 16u]);
    var normalized = vec4<f16>(0);
    normalized.x = f16(publish_fp8(f32(weight.x)));
    normalized.y = f16(publish_fp8(f32(weight.y)));
    normalized.z = f16(publish_fp8(f32(weight.z)));
    normalized.w = f16(publish_fp8(f32(weight.w)));
    vector_scores[linear] = normalized * vec4<f16>(4);
    packed_scores[linear] = packed_window_exponents(vec4<f32>(normalized));
  }
  workgroupBarrier();
  for (var linear = lane; linear < 256u; linear += 512u) {
    let query = linear / 8u;
    let first = (linear % 8u) * 4u;
    let qx = wx + i32((query_origin + query) % 8u);
    let qy = wy + i32((query_origin + query) / 8u);
    if (qx >= 0 && qx < i32(WINDOW_WIDTH) && qy >= 0 && qy < i32(WINDOW_HEIGHT)) {
      var word = 0u;
      for (var i = 0u; i < 4u; i++) {
        let component = first + i;
        var value = 0.0;
        for (var group = 0u; group < 4u; group++) {
          value = tiled_value(query, component, group * 16u, value);
        }
        word |= publish_e4_code(value) << (i * 8u);
      }
      let index = (u32(qy) * WINDOW_WIDTH + u32(qx)) * WINDOW_CHANNELS
        + head * 32u + first;
      attention_output[index / 4u] = word;
    }
  }
}
